917 fixing module timing
trisyoungs/duq pull request #1539
Opened 2023-07-18 13:41 UTC by rhinoella

## Changes made:
- Module `process()` functions return an enum instead of a bool
    - Enum has three types: `failed`, `success` and `notExecuted`
    - `notExecuted` is returned when the process legitimately fails (e.g process is not needed)
- Process time is only added to if `success` is returned
- Fixed small issue: when Simulation > Step is used, after running the step the ETA is set to `??:??:??`, now it goes back to `--:--:--`

2023-07-18 15:11 UTC, trisyoungs requested changes
A little bit of renaming and I think we're good!

2023-07-18 15:11 UTC, trisyoungs commented on src/module/module.cpp
> +enum Module::executionResult Module::process(Dissolve &dissolve, const ProcessPool &procPool) { return failed; }
You don't / shouldn't have to specify `enum Module::executionResult` here, just `Module::executionResult` - in fact, doing so adds a bit of clutter to the code.  Thankfully, a simple search/replace will get you there!

2023-07-18 15:11 UTC, trisyoungs commented on src/module/module.h
> +    };
Got my picky hat on today!  Our enum-naming convention is to capitalise the first letter as well. Also we can make this an `enum class` which enforces scope and type better.
```suggestion
    // Module execution result
    enum class ExecutionResult
    {
        Failed,
        Success,
        NotExecuted
    };
```

2023-07-18 15:11 UTC, trisyoungs commented on src/modules/accumulate/process.cpp
> +        return failed;
I don't recall whether using `enum class` will enforce this, but to me this makes the intent clearer:
```suggestion
        return ExecutionResult::Failed;
```

2023-07-19 15:35 UTC, trisyoungs requested changes
Looks a lot nicer - just need to tidy away that nasty `static_cast`!

2023-07-19 15:35 UTC, trisyoungs commented on src/main/simulation.cpp
> +                if (static_cast<int>(module->executeProcessing(*this, worldPool())) == 0)
Ick!  Let's not do this as it really hides intent, and kinda undoes all the niceness of `enum class`.  All we need to do is make the enum `public` in the `Module` class.
```suggestion
                if (module->executeProcessing(*this, worldPool()) == Module::ExecutionResult::Failed)
```

2023-07-19 15:35 UTC, trisyoungs commented on src/module/module.cpp
> +    }
Do we actually want to accumulate a zero here?  This will add to the statistics and effectively reduce the average time it takes for the module to run.  If we don't add anything then the `processTimes_` will reflect some sort of upper maximum time for the module.

2023-07-19 15:35 UTC, trisyoungs commented on src/module/module.cpp
> +    }
```suggestion
        processTimes_ += timer.secondsElapsed();
```

2023-07-19 15:35 UTC, trisyoungs commented on src/module/module.h
>      // Set frequency at which to run Module (relative to layer execution count)
```suggestion

    public:
    // Process exit information
    enum class ExecutionResult
    {
        Failed,
        Success,
        NotExecuted
    };
    // Set frequency at which to run Module (relative to layer execution count)
```

2023-07-20 10:17 UTC, rhinoella commented on src/module/module.cpp
> +    }
This was done because if processTimes_ was left empty, the ETA would flash on and off as it would encounter module processes returning `NotExecuted`, but now I will tackle that problem in the GUI code rather than the module timing!

2023-07-20 11:46 UTC, trisyoungs approved these changes
:+1:

2023-07-20 19:20 UTC, merged