Updating Developer Docs
trisyoungs/duq pull request #1545
Opened 2023-07-19 09:47 UTC by rhinoella

- Added instructions for Nix Setup in WSL 2
- Changed title from "Developing on IDAaas" to "Development Environment" and changed the description to make it less IDAaas-specific

Closes #1538.

2023-07-20 12:00 UTC, trisyoungs requested changes
Looks good - I was expecting the instructions to be way different!  Couple of comments, but I've only requested changes because we should rename the file from `idaaas.md` to `nix.md`.

2024-11-20 09:47 UTC, RobBuchananCompPhys commented on web/docs/userguide/developers/idaaas.md
> +
Just checked my own WSL2 installation, and it looks like you do need to `sudo` in the home directory!

2024-11-20 09:53 UTC, trisyoungs approved these changes

2024-11-20 09:53 UTC, trisyoungs commented on web/docs/userguide/developers/idaaas.md
> +
How very un-Linuxy!

2024-11-20 11:17 UTC, merged