Displaying elapsed time when running & fixed main loop timer
trisyoungs/duq pull request #1561
Opened 2023-07-22 21:56 UTC by rhinoella

### Elapsed time is now shown when running
![image](https://github.com/disorderedmaterials/dissolve/assets/101950441/fcf49c25-f31d-4c96-8ab0-ee701b3d086a)
### Main Changes:
- `iterationTimer_` (timer for the main loop) used to start/stop inside the `Dissolve::iterate()` function which is also iterated itself, meaning it was measuring the time for each iteration and not the total runtime
  - The starting/stopping of `iterationTimer_` is moved to `DissolveThreadWorker::beginIterating()` which calls `iterate()` in a loop
  - Start/stop timer is called through signals/slots (not sure if this is the ideal way to do this, but I could not think of another way)

2023-07-22 21:59 UTC, rhinoella commented
Also please let me know which format for displaying the time is preferred: "x hours, x minutes and x seconds" or "xx : xx : xx"

2023-07-23 20:01 UTC, trisyoungs requested changes
OK, so first off I think I prefer the X hours, Y minutes and Z seconds format, so let's stick with that. Second, I think it would be less confusing, and more easily implemented, to not try and use the current `Dissolve::iterationTimer_` and implement a new `elapsedTimer_` in the `DissolveWindow` class itself.  That way we don't have to worry about signals/slots for communication (which was the correct way, BTW).

2023-07-23 20:01 UTC, trisyoungs commented on src/base/timer.cpp
> +
This is a nice little function, but is so general that it should be available everywhere.  I suggest moving it to the `DissolveSys` namespace in `src/base/sysFunc.h`.

2023-07-23 20:01 UTC, trisyoungs commented on src/base/timer.cpp
> +    int seconds = duration.count() - hours * 3600 - minutes * 60;
Curious to know why you removed the `auto` and went to `int`?  Given two `int` arguments, the `/` operator returns an `int` and so `auto` is indeed valid here.

2023-07-25 10:01 UTC, rhinoella commented
I've made the requested changes and also kept `iterationTimer_` in the `printTiming()` function because I realised that `iterationTimer` reports the total elapsed time for people using Dissolve in the command-line, as in that case it does not loop over `iterate()`. 

### Changes:

- Moved `elapsedTimer_` to DissolveWindow class
- `plural()` has been moved from Timer class to DissolveSys
- Edited some of the Timer functions to work with `elapsedTimer` (should not affect other timers)
- Changed ETA when using 'Run For ...' to be in the format "x minutes and x seconds" instead of "--:--:--" for consistency

2023-07-25 14:38 UTC, trisyoungs requested changes
Looking good, but have made some suggestions for improvement / simplification.

2023-07-25 14:38 UTC, trisyoungs commented on src/base/sysFunc.cpp
> +
OK so this is interesting, but for a very annoying reason!  I want to say that the `double` overload is unnecessary, or at least a bit redundant, since when expressing time in string form as we are here, seconds is only singular when its exactly `1`.  Otherwise we're writing things like`1 minute and 0.5 seconds`, otherwise we'd have to write `1 minute and 0.5 of a second` which is just nasty.  I think I would suggest keeping just the `int` version, and making the string output always `seconds`.

2023-07-25 14:38 UTC, trisyoungs commented on src/base/timer.cpp
> +        return fmt::format("{:0.1f} second{}", seconds, DissolveSys::plural(seconds));
Suggesting to keep this as `seconds` for all values.

2023-07-25 14:38 UTC, trisyoungs commented on src/base/timer.cpp
> +std::string Timer::timeString(std::chrono::duration<double> duration, bool truncate)
There's a lot of code duplication between this function and `timeString(double seconds)` - I would suggest moving the code here (which is more flexible because of the `truncate` argument) and moving it to the other function, and just calling it from here as you do with `elapsedTimeString`.

2023-07-25 14:38 UTC, trisyoungs commented on src/gui/gui.h
> +    // Start run timer
```suggestion
```

2023-07-25 14:38 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    addStatusBarIcon(":/general/icons/general_clock.svg")->setToolTip("Timer");
"Timer" is not a particularly useful tooltip, and given the text label accompanying the time string values I think we probably don't need one here or on the `etaLabel_` any more.

2023-07-25 14:38 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
>      etaLabel_ = addStatusBarLabel("--:--:--");
This placeholder (HH:MM:SS) doesn't represent our format any more.

2023-07-25 14:38 UTC, trisyoungs commented on src/base/timer.h
> +    // Whether the timer has started before
Is this meant to mean "Whether the timer is currently running"?

2023-07-25 14:38 UTC, trisyoungs commented on src/gui/gui.h
>      QLabel *etaLabel_;
I think this warrants a name change, given the new purpose of the label.
```suggestion
    QLabel *timerLabel_;
```

2023-07-25 14:38 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    etaLabel_->setText("------------");
Instead of dashes, perhaps we mirror the main status indicator and say "Idle" or "Not running"? Regardless, since we set the text of the `etaLabel_` to some common string in at least three places it's probably worth adding that string as a `static constexpr` member in the main gui header, and using that instead.  Then if we want to change it there's a single source.

2023-07-27 14:09 UTC, rhinoella commented on src/base/timer.h
> +    // Whether the timer has started before
It is whether or not the timer has been started before , it is essentially there because the elapsed timer text is set in the `updateStatusBar()` function and it needs to know whether or not the `elapsedTimer_` is running (`started_ == true`), and that means it should be displaying time elapsed. As we are calling this in the `DissolveWindow` class, it doesn't know whether or not `dissolveIterating_` is true due to the user hitting 'Run' or 'Run For' (would instead need to display ETA).

2023-07-27 14:23 UTC, rhinoella commented
### Changes
- Removed overloaded `plural()` function
- Merged the two `timeString()` functions together

2023-08-04 12:20 UTC, trisyoungs reviewed
Looking pretty good!  Few minor suggestions here and there.

I wonder if we should prefix the time strings with either "Time Elapsed: " or "Time Remaining: ", depending on the context, to make things clear?

I also notice that  after running normally (i.e. not for a set number of steps) the time elapsed remains shown, rather than reverting to the default text.

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/gui.h
> +    static constexpr const char *timerText_ = "Idle";
I appreciate that this is the only reasonable way of defining our default text in the header, but it's a bit "archaic C", so I'd suggest we move it to the `guiFuncs.cpp` file since that's the only place its used.
```suggestion
```

In between the `#include`s and the constructor:
```
// Default timer text
const QString defaultTimerText{"Idle"};
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/gui.h
> +    Timer elapsedTimer_ = Timer(false);
Prefer brace initialisation:
```suggestion
    // Main loop iteration timer
    Timer elapsedTimer_{Timer(false)};
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    timerLabel_ = addStatusBarLabel(timerText_);
```suggestion
    timerLabel_ = addStatusBarLabel(defaultTimerText);
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    timerLabel_->setText(timerText_);
```suggestion
    timerLabel_->setText(defaultTimerText);
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +            QString::fromStdString(elapsedTimer_.hasStarted() ? elapsedTimer_.elapsedTimeString(true) : timerText_));
```suggestion
        timerLabel_->setText(elapsedTimer_.hasStarted() ? 
            QString::fromStdString(elapsedTimer_.elapsedTimeString(true)) : defaultTimerText);
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +
```suggestion
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    }
For one-liners after an `if` I tend to omit the braces. Why take up three lines when you only need one!
```suggestion
    if (iterationsRemaining == -1)
        timerLabel_->setText(QString::fromStdString(elapsedTimer_.elapsedTimeString(true)));
```

2023-08-04 12:20 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +                                           : timerText_);
```suggestion
        timerLabel_->setText(estimatedTime ? QString::fromStdString(Timer::timeString(estimatedTime.value(), false))
                                           : defaultTimerText);
```

2023-08-07 15:28 UTC, rhinoella commented
![image](https://github.com/disorderedmaterials/dissolve/assets/101950441/2b3452c5-5837-4a7c-94eb-05be896ab9f1)

### Comments:
- When stopping an infinite run, the timer label remains displaying the time elapsed
- When a run of specified iterations finishes, the timer label displays the default text ('Idle')

2023-08-08 12:23 UTC, trisyoungs approved these changes
One teeny-tiny comment, but this all looks good and works really nicely.

2023-08-08 12:23 UTC, trisyoungs commented on src/gui/guiFuncs.cpp
> +    else if (!dissolveIterating_ && elapsedTimer_.secondsElapsed() != 0.0)
I always find exact comparison of `double` values a bit dubious when used in logic statements, so suggesting a greater-than instead.
```suggestion
    else if (!dissolveIterating_ && elapsedTimer_.secondsElapsed() > 0.0)
```

2023-08-08 12:43 UTC, merged