1548 Calculate errors over a specific range
trisyoungs/duq pull request #1569
Opened 2023-07-25 12:42 UTC by rhinoella

Closes #1548

2023-07-25 13:51 UTC, rhinoella commented
### Changes
- All error functions now accept a range parameter
- Range has a default object (does not need to be specified)

2023-07-26 12:44 UTC, trisyoungs requested changes
Good case for a `std::optional` I think! See comments below.

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
> +double error(ErrorType errorType, const Data1D &A, const Data1D &B, bool quiet, Range range)
Two things to say about the functions in general: 1) I think the `Range` argument should legitimately come before the `bool quiet` flag in terms of importance, and; 2) if we use a `std::optional<Range>` this gives us a better ability to check whether a `Range` has actually been supplied, rather than comparing the `minimum()` and `maximum()` for equality. This isn't the only "invalid" range condition, so I think we have to leave that as the responsibility of the user / coder.

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
> +    }
With `std::optional<Range>` as our argument, we could do some checks here, but we would have to do the same check for every function since they're generally accessible. So, I would remove the check here and modify the checks in the individual functions...
```suggestion
```

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
> +double error(ErrorType errorType, const std::vector<double> &vecA, const std::vector<double> &vecB, bool quiet, Range range)
We should leave this particular function be as a "non-Rangable" error check - since we're artificially creating the `Data1D` anyway an applied `Range` is kinda meaningless.  This function was introduced to handle a few specific test cases, so is specialised use anyway.

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
> +double rmse(const Data1D &A, const Data1D &B, bool quiet, Range range)
Switch order of `bool quiet` and `std::optional<Range> range` as suggested.

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
> +    }
What I suggest we do here, given our `std::optional<Range>` argument, is establish the relevant limits in some temporary vars, and check those vars in the main loop:
```suggestion
    // Set calculation range
    auto rangeMin = range ? range.minimum() : B.xAxis().front();
    auto rangeMax = range ? range.maximum() : B.xAxis().back();
```

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.cpp
>              break;
This can then be something like:
```
            // Check range
            if (x < rangeMin)
                continue;
            if (x > rangeMax)
                break;
```

2023-07-26 12:44 UTC, trisyoungs commented on src/math/error.h
> +double rmse(const Data1D &A, const Data1D &B, bool quiet = false, Range range = Range());
```suggestion
double rmse(const Data1D &A, const Data1D &B, std::optional<Range> range = {}, bool quiet = false);
```
etc.

2023-07-27 11:48 UTC, rhinoella commented
### Changes
- Range parameter is now an `OptionalReferenceWrapper<Range>`
- Removed `bool quiet` parameter (not Error's job to print output now)
- All functions now return an `ErrorReport` struct that contains all the information needed to print an error report
- New error function `ase()` (and corresponding error type `ASEError`) returns absolute squared error (this used to happen in the `percent()` function, if sum of y values is zero it returned ase instead to avoid dividing by zero)
  - This is one of the reasons I chose to have the functions return a struct, so that the caller of `percent()` would be able to know that they are getting ase error instead of percent error

2023-07-28 16:49 UTC, trisyoungs approved these changes
Couple of minor bits, but this is nice.   I like the little `ErrorReport` object - that's a neat thing.

2023-07-28 16:49 UTC, trisyoungs commented on src/math/error.h
> +    double value;
Semantics here, but do you think this should be called `double error` rather than `double value`?

2023-07-28 16:49 UTC, trisyoungs commented on src/math/error.h
> +// Return error of specified type between supplied data, allows a range parameter to be specified
```suggestion
// Return error of specified type between supplied data over all points or the range given
```

2023-07-28 16:49 UTC, trisyoungs commented on src/modules/gr/functions.cpp
> +    Error::ErrorReport error;
I think its safer / neater if this is moved inside the loop.
```suggestion
```

2023-07-28 16:49 UTC, trisyoungs commented on src/modules/gr/functions.cpp
>              error = Error::percent(setA.partial(n, m), setB.partial(n, m));
```suggestion
            auto error = Error::percent(setA.partial(n, m), setB.partial(n, m));
```

2023-07-28 16:49 UTC, trisyoungs commented on src/math/error.h
> +std::string errorReportString(ErrorReport errorReport);
Only a simple `struct` I know, but you may as well make this a `const &` to ensure it doesn't get modified in the function.
```suggestion
std::string errorReportString(const ErrorReport &errorReport);
```

2023-07-31 14:56 UTC, merged