Layer Keyword
trisyoungs/duq pull request #1570
Opened 2023-07-25 14:41 UTC by jws-1

This PR implements a `Layer` keyword and an associated widget, for usage in nodes. Also moves `processingLayers_` (and the relevant member functions) to `CoreData`. The addition of this keyword does not have any implications currently, in terms of functionality, but it will be useful for #88 (and currently #1565)..

![image](https://github.com/disorderedmaterials/dissolve/assets/100244619/0c65a222-e966-4013-9b81-dc522f06838e)

2023-07-26 14:14 UTC, trisyoungs requested changes
Yep, I think moving the layers to `CoreData` feels very much like the right thing to do.  Have made a few notes on implementation of the keyword itself, and a bug or two to squash.

2023-07-26 14:14 UTC, trisyoungs commented on src/keywords/layer.cpp
> +SerialisedValue LayerKeyword::serialise() const { return data_->name(); }
Need to check for the validity of `data_` before accessing it, just to be on the safe side.

2023-07-26 14:14 UTC, trisyoungs commented on src/keywords/layer.cpp
> +    data_ = coreData.findProcessingLayer(std::string_view(std::string(node.as_string())));
Need to check for the layer's existence and `throw` if it isn't there (see e.g. `ModuleKeyword` equivalent).

2023-07-26 14:14 UTC, trisyoungs commented on src/main/layers.cpp
>  }
Kinda feel like this should be part of `CoreData` too since it only operates on data local to it, but of course we pass in the `Dissolve` object by necessity.  Worth capturing the test of whether `Module`s really need `Dissolve` and can cope with just `CoreData` as a separate issue, and flag this function to be moved if so.

2023-07-26 14:14 UTC, trisyoungs commented on src/gui/keywordWidgets/layerFuncs.cpp
> +    ui_.LayerCombo->setCurrentIndex(-1);
Need to set the combo to the correct index based on the current data, rather than "no item":
```suggestion
    // Set current index based on keyword data
    auto it = std::find(coreData_.processingLayers().begin(), coreData_.processingLayers().end(), keyword_->data());
    ui_.LayerCombo->setCurrentIndex(it == coreData_.processingLayers().end() ? -1 : it - coreData_.processingLayers().begin());
```
Something like this, anyway!

2023-07-27 09:27 UTC, trisyoungs requested changes
Another iteration required here, but mostly just to tidy a few things I spotted / realised.

2023-07-27 09:27 UTC, trisyoungs commented on src/classes/coreData.cpp
> +
Don't we need this in here?
```suggestion

    // Remove any references to the Modules in the layer before we delete it
    for (auto &module : layer->modules())
        removeReferencesTo(module.get());
        
```

2023-07-27 09:27 UTC, trisyoungs commented on src/classes/coreData.cpp
> +
I believe these are both unused, old functions so can be removed.
```suggestion
```

2023-07-27 09:27 UTC, trisyoungs commented on src/classes/coreData.cpp
> +// Return list of defined processing layers
```suggestion
// Return current processing layers
```

2023-07-27 09:27 UTC, trisyoungs commented on src/classes/coreData.h
> +    int nProcessingLayers() const;
I believe these are both unused, old functions so can be removed.
```suggestion
```

2023-07-27 09:27 UTC, trisyoungs commented on src/classes/coreData.h
> +    // Return list of defined processing layers
```suggestion
    // Return current processing layers
```

2023-07-27 09:27 UTC, trisyoungs commented on src/keywords/layer.cpp
> +        return Messenger::error("Error setting Layer - no Layer named '{}' exists.\n", parser.argsv(startArg));
For consistency.
```suggestion
        return Messenger::error("Layer '{}' given to keyword {} doesn't exist.\n", parser.argsv(startArg), KeywordBase::name());
```

2023-07-27 09:27 UTC, trisyoungs commented on src/main/dissolve.h
>       */
This needs renaming now:
```suggestion
     * Processing Module Data
     */
```

2023-07-27 09:27 UTC, trisyoungs commented on src/main/layers.cpp
This file now only contains a single function and is the "wrong" name, so I think we should move that function to `dissolve.cpp` under the renamed heading ("Processing Module Data") and delete this file.

2023-07-27 10:43 UTC, jws-1 commented on src/classes/coreData.cpp
> +
Yes, we probably do!

2023-07-31 15:44 UTC, trisyoungs approved these changes

2023-07-31 16:16 UTC, merged