Show Applied Size Factor
trisyoungs/duq pull request #1579
Opened 2023-07-27 10:40 UTC by jws-1

This PR updates the Configuration tab to show the applied size factor, if it is not equal to the default value (of 1.0). Only blocker here is that I couldn't decide on a suitable icon to pair with the frame.

Closes #1578.

2023-07-27 14:40 UTC, trisyoungs approved these changes
Yep, exactly this!  I'll address the icon in an upcoming PR with a bunch of others which are currently missing / need updating.

Left a comment on the actual size factor member variables for you to muse on, but I'll approve this PR.

2023-07-27 14:40 UTC, trisyoungs commented on src/gui/configurationTabFuncs.cpp
> +    ui_.SizeFactorFrame->setVisible(configuration_->appliedSizeFactor() != 1.0);
Comparing real numbers always feels a bit "risky" because of rounding.  I wonder if this is a good opportunity to change both `appliedSizeFactor_` and `requestedSizeFactor_` member variables to be `std::optional<double>`s? Then, things are absolutely clear, and we avoid checking for `1.0` as an effective "magic number".

2023-07-28 08:50 UTC, trisyoungs requested changes
Yes, I think optionals were the way to go, but let's use their full power! :)

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration.h
> +    static double defaultSizeFactor();
I think we don't need this..
```suggestion
```

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration_box.cpp
> +
```suggestion
```

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration_box.cpp
> +            requestedSizeFactor_.value_or(defaultSizeFactor_) / appliedSizeFactor_.value_or(defaultSizeFactor_);
It feels like we should tidy this up and do both `value_or` retrievals into a couple of temporary variables (`requestedSF` and `appliedSF` perhaps) before the `while` loop.

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration_box.cpp
> +                             requestedSizeFactor_.value_or(defaultSizeFactor_));
It definitely has a value here as well as in a few lines above, so:
```suggestion
                             *requestedSizeFactor_);
```

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration_box.cpp
>          }
At the end of the function, if `appliedSizeFactor_` is now (within error) equal to `1.0` we can set it to `std::nullopt`.

2023-07-28 08:50 UTC, trisyoungs commented on src/classes/configuration_io.cpp
> +    scaleBox({appliedSizeFactor_.value_or(defaultSizeFactor_), appliedSizeFactor_.value_or(defaultSizeFactor_),
```suggestion
    auto appliedSF = appliedSizeFactor_.value_or(defaultSizeFactor_);
    scaleBox({appliedSF, appliedSF, appliedSF});
```

2023-07-28 08:50 UTC, trisyoungs commented on src/module/layer.cpp
> +                                   2 * std::numeric_limits<double>::epsilon();
```suggestion
                            return cfg->appliedSizeFactor();
```

2023-07-31 09:29 UTC, trisyoungs approved these changes
One tiny and almost irrelevant suggestion, then good to go! :+1:

2023-07-31 09:29 UTC, trisyoungs commented on src/gui/configurationTabFuncs.cpp
> +    ui_.SizeFactorLabel->setText(QString::number(configuration_->appliedSizeFactor().value_or(0.0)));
Picky, I know, but the `0.0` doesn't represent a valid size factor (even if it isn't being shown!)
```suggestion
    ui_.SizeFactorLabel->setText(configuration_->appliedSizeFactor() ? QString::number(*configuration_->appliedSizeFactor() : "N/A"));
```

2023-07-31 09:32 UTC, jws-1 commented on src/gui/configurationTabFuncs.cpp
> +    ui_.SizeFactorLabel->setText(QString::number(configuration_->appliedSizeFactor().value_or(0.0)));
I was getting ready to defend this, but I think your option is better.

2023-07-31 12:15 UTC, merged