1548 error range keyword
trisyoungs/duq pull request #1585
Opened 2023-07-28 12:40 UTC by rhinoella

This PR implements a new keyword type of `std::vector<Range>` to get R Factors over specific data ranges.

2023-07-28 18:22 UTC, trisyoungs requested changes
Almost there. Naming needs some generalisation, and a couple of bits to correct, but otherwise looks like the keyword we need!

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/CMakeLists.txt
> +  rFactorRangesVector.cpp
We'll be able to use this new keyword in any context, so we should call it just
```suggestion
  rangeVector.cpp
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/CMakeLists.txt
> +  rFactorRangesVector.h
```suggestion
  rangeVector.h
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/base.cpp
> +}
No need to implement an overloaded function for `Range` objects - these `removeReferencesTo` functions cater explicitly for dynamically-allocated objects that the user has control over (in the sense of being able to destroy them). `Range` doesn't fall into this category.
```suggestion
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/base.h
> +#include "math/range.h"
```suggestion
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/base.h
> +    virtual void removeReferencesTo(Range range);
```suggestion
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +RFactorRangesVector::RFactorRangesVector(std::vector<Range> &data) : KeywordBase(typeid(this)), data_(data) {}
In line with earlier suggestions, and adding on the missing `Keyword` suffix to denote it as such, the class should be called `RangeVectorKeyword`:
```suggestion
RangeVectorKeyword::RangeVectorKeyword(std::vector<Range> &data) : KeywordBase(typeid(this)), data_(data) {}
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +                                    parser.argsv(n));
Slight adjustment to the message, and include the keyword `name()` for the user's benefit:
```suggestion
            return Messenger::error("Value '{}' provided to keyword '{}' doesn't appear to be a number.\n",
                                    parser.argsv(n), name_);
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +    for (auto range : data_)
Might as well use references to avoid the copy:
```suggestion
    for (auto &range : data_)
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +
```suggestion
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +                      [](const auto item) -> SerialisedValue {
```suggestion
                      [](const auto &item) -> SerialisedValue {
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.cpp
> +    }
Can use @rprospero's nice `toVector` function here:
```suggestion
    toVector(node,
             [this](const auto &item)
             {
                 data_.emplace_back(toml::find<double>(item, "minimum"), toml::find<double>(item, "maximum"));
             });
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.h
> +#include "module/module.h"
```suggestion
```

2023-07-28 18:22 UTC, trisyoungs commented on src/keywords/rFactorRangesVector.h
> +    public:
```suggestion
```

2023-08-03 15:44 UTC, rhinoella commented
Please note that I merged `origin/develop` into this branch because I needed the recent changes to `error.h` and `error.cpp` but unfortunately it also included all the file deletions from other changes into my commits. Not sure how to fix this, but to have an easier time viewing my changes you can go to files changed > File filter > uncheck Deleted files.

2023-08-03 15:47 UTC, rhinoella commented
## Changes

Added RFactorRanges keyword to the EPSR module:

![image](https://github.com/disorderedmaterials/dissolve/assets/101950441/afbddb1b-c0cb-480c-a765-5f2cf664d3d6)
(Invalid ranges are highlighted in red)

- Invalid ranges are checked for in `EPSRModule::process()` and produce a warning in the messenger and are skipped in calculations
- Current & total RFactors over the specified ranges are printed to the messenger

2023-08-04 13:00 UTC, trisyoungs requested changes
Picked up some CMake formatting errors in the CI: https://github.com/disorderedmaterials/dissolve/actions/runs/5752825655/job/15594663796#step:17:218

I would say that, while this is not a huge PR, it adds a lot of related but different components, and would have been more manageable as a series of smaller PRs.

I think at some point we mentioned having the RFactorRanges keyword in a separate section in the Advanced options?

Anyway, lots to like here, but lots of small suggestions from me to get this in to shape.

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/keywordWidgets/CMakeLists.txt
May we have these new source files inserted in alphabetical order please? It'll make me happy!

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/keywordWidgets/producers.cpp
> +    registerProducer<RangeVectorKeyword, RangeVectorKeywordWidget>();
Similarly, alphabetical ordering please!

2023-08-04 13:00 UTC, trisyoungs commented on src/modules/epsr/gui/epsrWidget.ui
> +        <string>Show the calculated vs experimental F(Q)</string>
Good eye!

2023-08-04 13:00 UTC, trisyoungs commented on src/keywords/CMakeLists.txt
Alphabetic ordering.

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/CMakeLists.txt
Alphabetic ordering.

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    }
```suggestion
        return {};
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +            if ((index.column() == 1 || index.column() == 2) && getRange(index)->maximum() < getRange(index)->minimum())
We do this check (min < max) a few times, and it might be a better idea to add a function in to the `Range` class itself, rather than access both elements as is done here.  I guess we call it `isValid()` and also check for min == max at the same time?

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
The blank line police are out in force today!
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
    Q_UNUSED(count);
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
    Q_UNUSED(count);
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    }
```suggestion
        return false;
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
            return false;
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
            return false;
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    }
```suggestion
        return Qt::ItemIsSelectable | Qt::ItemIsEnabled;
    else
        return Qt::ItemIsSelectable | Qt::ItemIsEnabled | Qt::ItemIsEditable;
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +
```suggestion
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +Range *RangeModel::getRange(const QModelIndex &index) const { return &ranges_->get()[index.row()]; }
May as well return a reference here, no? But you might want to add a few other checks (e.g. index.isValid()) to try and catch the obvious segfault.
```suggestion
Range &RangeModel::getRange(const QModelIndex &index) const { return ranges_->get()[index.row()]; }
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/keywordWidgets/rangeVector.ui
> +                                <normaloff>:/general/icons/general_add.svg</normaloff>:/general/icons/general_add.svg</iconset>
```suggestion
                                <normaloff>:/general/icons/add.svg</normaloff>:/general/icons/add.svg</iconset>
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/keywordWidgets/rangeVector.ui
> +                                <normaloff>:/general/icons/general_remove.svg</normaloff>:/general/icons/general_remove.svg</iconset>
```suggestion
                                <normaloff>:/general/icons/remove.svg</normaloff>:/general/icons/remove.svg</iconset>
```

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
Strictly this should be called `RangeVectorModel`, and the source files `rangeVectorModel.cpp` and `rangeVectorModel.h` for consistency.

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    // TO CONVERT VALUE TO DOUBLE AND STRING
Allow me to ask current Noella what the particular issue is here? Perhaps I can help!

2023-08-04 13:00 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    auto range = getRange(index);
If you do change `getRange` to return a reference, don't forget to do `auto &range` here as well.

2023-08-04 13:41 UTC, rhinoella commented on src/gui/models/rangeModel.cpp
> +    // TO CONVERT VALUE TO DOUBLE AND STRING
Apologies, I write notes to myself at the end of the day so that I can pick up where I left off the next day, I forgot to delete this one though

2023-08-04 20:30 UTC, trisyoungs commented on src/gui/models/rangeModel.cpp
> +    // TO CONVERT VALUE TO DOUBLE AND STRING
It's all good.  I do the same, but my notes to self tend to be rather more "impolite"!

2023-08-08 15:49 UTC, trisyoungs requested changes
All looking very nice.  A sprinkling of suggestions, as usual! :)

2023-08-08 15:49 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    int rFacCount = 0;
```suggestion
    auto rFacCount = 0;
```

2023-08-08 15:49 UTC, trisyoungs commented on src/math/range.cpp
>  void Range::set(double minimum, double maximum)
Do we really need this overloaded version of `set()` now? Everything can be handled by the `std::optional<double>` variant.

2023-08-08 15:49 UTC, trisyoungs commented on src/math/range.cpp
> +bool Range::isDefined() const { return (minimum_ && maximum_) ? true : false; }
```suggestion
bool Range::isDefined() const { return (minimum_ && maximum_); }
```

2023-08-08 15:49 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    std::vector<double> rangedRFacTots(targets_.size() * ranges_.size());
Shouldn't this be
```suggestion
    std::vector<double> rangedRFacTots(ranges_.size());
```

2023-08-08 15:49 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +        }
```suggestion
        for (auto &&[range, rangeTot] : zip(ranges_, rangedRFacTots))
        {
            rFactor = Error::rFactor(tempRefData, weightedSQ.total(), range).error;
            rangeTot += rFactor;
            Messenger::print("Current R-Factor for reference data '{}' over range {:.5f} to {:.5f} is {:.5f}.\n",
                             module->name(), range.minimum(), range.maximum(), rFactor);
        }
```

2023-08-08 15:49 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    }
```suggestion
    for (auto &&[range, rangeTot] : zip(ranges_, rangedRFacTots))
    {
        Messenger::print("Current total R-Factor over range {:.5f} to {:.5f} is {:.5f}.\n", range.minimum(),
                         range.maximum(), rangeTot /= targets_.size());
    }
```

2023-08-08 15:49 UTC, trisyoungs commented on src/math/range.cpp
>      return true;
You could one-line this if you wanted to:
```suggestion
    return isDefined() && (d >= minimum_) && (d <= maximum_);
```

2023-08-08 15:49 UTC, trisyoungs commented on src/keywords/rangeVector.cpp
> +        }
```suggestion
        if (range.isDefined() && !parser.writeLineF("{}{}  {}  {}\n", prefix, keywordName, range.minimum(), range.maximum()))
        {
            return false;
        }
```

2023-08-08 15:49 UTC, trisyoungs commented on src/math/range.cpp
> +    maximum_ = std::max(minimum, maximum);
Since you're not checking here whether the `std::optional`s contain valid values, its much safer to use your `set()` function, I would say:
```suggestion
    set(minimum, maximum);
```

2023-08-10 09:54 UTC, rhinoella commented on src/math/range.cpp
>  void Range::set(double minimum, double maximum)
I think it is needed, the intention is that `set(std::optional<double> minimum, std::optional<double> maxiumum) is a `private` function while `set(double minimum, double maximum)` is `public`. This ensures that `minimum` and `maximum` can only be set as `nullptr` in the default constructor, and outside of that only valid ranges can be set. What do you think?

2023-08-15 11:43 UTC, trisyoungs requested changes
A few final comments and suggestions on this, since we are messing with a core "reportable" of the module!  Got to get it right.

2023-08-15 11:43 UTC, trisyoungs commented on src/math/range.cpp
>  void Range::set(double minimum, double maximum)
OK, I see your intent now. That makes sense, so lets keep it as-is.

2023-08-15 11:43 UTC, trisyoungs commented on src/gui/keywordWidgets/rangeVectorFuncs.cpp
> +    // Update allowed modules
```suggestion
```

2023-08-15 11:43 UTC, trisyoungs commented on src/gui/models/rangeVectorModel.cpp
> +    ranges_->get().emplace_back();
This assumes that we're always appending at the end of the vector, whereas in reality the new entry is at position index `row`, so you might want to change this to use `insert()` instead just to make the model strictly correct.

2023-08-15 11:43 UTC, trisyoungs commented on src/keywords/rangeVector.cpp
> +        }
This nested `if` kinda sticks out a bit for me - I appreciate that you can explicitly report the offending value string this way, but perhaps this looks nicer:
```suggestion
        if (DissolveSys::isNumber(parser.argsv(n)) && DissolveSys::isNumber(parser.argsv(n + 1)))
        {
            data_.emplace_back(parser.argd(n + 1), parser.argd(n));
        }
        else
        {
            return Messenger::error("Range ({} to {}) given to keyword '{}' doesn't appear to be numerical.\n",
                                    parser.argsv(n), parser.argsv(n + 1), name());
        }
```

2023-08-15 11:43 UTC, trisyoungs commented on src/keywords/rangeVector.cpp
> +        }
I'll have another go at a suggestion here! :)
```suggestion
        if (range.isDefined())
        {
            if (!parser.writeLineF("{}{}  {}  {}\n", prefix, keywordName, range.minimum(), range.maximum()))
            {
                return false;
            }
        }
```

2023-08-15 11:43 UTC, trisyoungs commented on src/math/range.h
> +    void set(std::optional<double> minimum, std::optional<double> maximum);
Unwritten code convention suggests that member variables are separate from functions for clarity:
```suggestion
    std::optional<double> minimum_, maximum_;

    private:
    // Set range
    void set(std::optional<double> minimum, std::optional<double> maximum);
```

2023-08-15 11:43 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +        auto rFactor = errorReport.error;
Do we need to extract the values from the result into temporaries?  We only use them once in the case of the bounds.
```suggestion
        const auto rFactorReport = Error::rFactor(tempRefData, weightedSQ.total());
```

2023-08-15 11:43 UTC, trisyoungs commented on src/modules/epsr/process.cpp
>          errors.addPoint(moduleContext.dissolve().iteration(), rFactor);
This would then become...
```suggestion
        rFacTot += rFactorReport.error;
        errors.addPoint(moduleContext.dissolve().iteration(), rFactorReport.error);
```

2023-08-15 11:43 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +                         module->name(), lowerBound, upperBound, rFactor);
And...
```suggestion
                         module->name(), rFactorReport.firstX, rFactorReport.lastX, rFactorReport.error);
```

2023-08-15 11:43 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +                             module->name(), range.minimum(), range.maximum(), rFactor);
Regarding this piece of code, here we report the range bounds as defined, but above we reported the first and last points considered. Should we change this to report the actual data range over which the error was calculated to ensure there is no mistaking what the value represents?
```suggestion
            const auto rFactorRangeReport = Error::rFactor(tempRefData, weightedSQ.total(), range).error;
            rangeTot += rFactorRangeReport.error;
            Messenger::print("Current R-Factor for reference data '{}' over range {:.5f} to {:.5f} is {:.5f}.\n",
                             module->name(), range.minimum(), range.maximum(), rFactorRangeReport.error);
```

2023-08-15 11:43 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +    Messenger::print("Current total R-Factor over complete range ({:.5f} to {:.5f}) is {:.5f}.\n", lowerBound, upperBound,
Here we report the full range over which the errors were calculated, but I think we need to be a bit more vague since the available data ranges for individual datasets can vary (e.g. x-ray data tends to be over a narrower Q-scale). So, reporting the range here is difficult to do in a meaningful way, and I think we should just report the total error.

2023-08-15 15:56 UTC, rhinoella commented on src/keywords/rangeVector.cpp
> +        }
What about:

```suggestion
        if (DissolveSys::isNumber(parser.argsv(n)) && DissolveSys::isNumber(parser.argsv(n + 1)))
        {
            data_.emplace_back(parser.argd(n + 1), parser.argd(n));
        }
        else
        {
            return Messenger::error("Value '{}' given to keyword '{}' doesn't appear to be numerical.\n",
                                    DissolveSys::isNumber(parser.argsv(n)) ? parser.argsv(n + 1) : parser.argsv(n), name());
        }
```

2023-08-16 08:26 UTC, trisyoungs commented on src/keywords/rangeVector.cpp
> +        }
Yeah, OK, let's go with that!  I also just noticed that your range is initialised with the two arguments in the "wrong" order (n+1, n)....

2023-08-16 09:46 UTC, rhinoella commented on src/modules/epsr/process.cpp
> +                             module->name(), range.minimum(), range.maximum(), rFactor);
So do you mean to report it as:
```
Messenger::print("Current R-Factor for reference data '{}' over range {:.5f} to {:.5f} is {:.5f}.\n",
                             module->name(), rFactorRangeReport.firstX, rFactorRangeReport.lastX, rFactorRangeReport.error);
```

Just for further clarification, the reason I decided to include the data's total range in the above report was that I thought it would be helpful for people to know the range of the whole data, as it might help with selecting ranges.

2023-08-23 20:55 UTC, trisyoungs approved these changes
I think this all looks OK.  Let's get it merged in and start testing it in earnest!

2023-08-24 09:57 UTC, merged