IfValueInRange Node
trisyoungs/duq pull request #1590
Opened 2023-07-31 15:42 UTC by trisyoungs

This PR introduces a new node in what is likely to become a series of useful "logic" additions to procedure writing in Dissolve.  The `IfValueInRange` node checks a given value (as a `NodeValue` expression) against a defined `Range`, only executing its "Then" branch if the value is within the specified limits.

Some other notable changes were made in order to allow this PR - principally, a sequence node can inherit the context from the encompassing (owning) parent sequence.  This is useful / necessary when introducing fully generic nodes like this one, and was technically already a feature in the code but it turned out to be horribly broken!

2023-08-02 07:33 UTC, jws-1 requested changes
Can't add a node to the branch as a `std::runtime_error` is thrown (see above comment)!

2023-08-02 07:33 UTC, jws-1 commented on src/procedure/nodes/ifValueInRange.cpp
> +            return false;
```suggestion
        return thenBranch_.execute(procedureContext);
```

2023-08-02 07:33 UTC, jws-1 commented on src/procedure/nodes/node.cpp
> +        throw(std::runtime_error(fmt::format("Attempted to context check node '{}' with an InheritedContext.\n")));
```suggestion
        throw(std::runtime_error(fmt::format("Attempted to context check node '{}' with an InheritedContext.\n", !name_.empty() ? name_ : nodeTypes().keyword(type_))));
```

Missing argument here. Although I'm not 100% convinced by this check, since when I add an `IfValueInRange` node and then try and add another node in the branch, this gets thrown.

2023-08-02 07:54 UTC, trisyoungs commented on src/procedure/nodes/node.cpp
> +        throw(std::runtime_error(fmt::format("Attempted to context check node '{}' with an InheritedContext.\n")));
Interesting.   I was only testing via an input file, not the GUi, so obviously missed something here!

2023-08-03 08:11 UTC, jws-1 approved these changes

2023-08-03 09:47 UTC, merged