1455 orientational sdf
trisyoungs/duq pull request #1627
Opened 2023-08-09 08:10 UTC by trisyoungs

### Builds off #1623

This PR adds in an `OrientedSDF` module, a variant of the `SDF` module which allows the selection of sites depending on the angle between specified axes.

No icon is added here, pending #1626.

Closes #1455.

2023-08-17 21:38 UTC, jws-1 requested changes
A few minor comments, waiting to review `orientedSDFWidgetFuncs.cpp` due to the widget not being displayed (as discussed).

2023-08-17 21:38 UTC, jws-1 commented on web/docs/userguide/modules/analysis/orientedsdf/_index.md
> +|`Symmetric`|`bool`|`false`| Whether to consider the angle as symmetric about 90, mapping all angles to the 0-90 range. For instance, if the target axes are perpendicular to a mirror plane in the mol
```suggestion
|`Symmetric`|`bool`|`false`| Whether to consider the angle as symmetric about 90, mapping all angles to the 0-90 range. For instance, if the target axes are perpendicular to a mirror plane in the molecule, this should be set to `true`.|
```

2023-08-17 21:38 UTC, jws-1 commented on src/modules/orientedSDF/process.cpp
> +    context.setProcessingDataPrefix(name());
I assume this will utilise #1628?

2023-08-17 21:38 UTC, jws-1 commented on src/modules/orientedSDF/orientedSDF.h
> +class SpeciesSite;
```suggestion
```

2023-08-17 21:38 UTC, jws-1 commented on src/modules/orientedSDF/orientedSDF.cpp
> +                                              rangeY_.x, rangeY_.y, rangeY_.z, rangeZ_.x, rangeZ_.y, rangeZ_.z);
Would be nicer if we could just pass three `Vec3<double>`s here, although not a necessity.

2023-08-17 21:38 UTC, jws-1 commented on src/modules/orientedSDF/orientedSDF.cpp
> +        "SiteB", "Set the site(s) 'B' for which the distribution around the origin sites 'A' should be calculated",
```suggestion
        "SiteB", "Set the site(s) 'B' for which the distribution around the origin site(s) 'A' should be calculated",
```

2023-08-21 21:52 UTC, trisyoungs commented on src/modules/orientedSDF/process.cpp
> +    context.setProcessingDataPrefix(name());
Yes - this will be retrofitted into #1628 before that PR gets merged.

2023-08-21 21:52 UTC, trisyoungs commented on src/modules/orientedSDF/orientedSDF.cpp
> +                                              rangeY_.x, rangeY_.y, rangeY_.z, rangeZ_.x, rangeZ_.y, rangeZ_.z);
I agree.  Not sure why we don't do that already, but there you go!  I'll change this before merge.

2023-08-22 08:43 UTC, jws-1 reviewed
I can now see the output tab! One minor question before approving - after running, I can't see anything for the `SDF` within it, but I can see the respective reference molecules if I select them. Should I be seeing anything additional?

2023-08-22 22:46 UTC, trisyoungs commented
The lower cutoff you need to set on the 3D display is quite low - `1.0e-3` should show you some "halos" of density above and below the ring. The default "guess" by the module is nowhere near this!

2023-08-23 08:41 UTC, jws-1 commented
> The lower cutoff you need to set on the 3D display is quite low - 1.0e-3 should show you some "halos" of density above and below the ring. The default "guess" by the module is nowhere near this!

![image](https://github.com/disorderedmaterials/dissolve/assets/100244619/6ccbf1bf-de55-44a3-969b-ae7b47e82685)

Something like this?

2023-08-23 16:44 UTC, trisyoungs commented
@jws-1 More or less!  If you rotate the view so you're looking "edge on" to the benzene rather than face on as above, you should see density above and below the plane of the ring.

2023-08-23 19:07 UTC, jws-1 approved these changes

2023-08-24 16:04 UTC, merged