Setup of iteratedata1d
trisyoungs/duq pull request #1632
Opened 2023-08-11 13:14 UTC by Danbr4d

2023-08-17 08:06 UTC, trisyoungs requested changes
I think this is exactly what we're after.  Just small comments and suggestions again, and you also need to create the parameter variables  in the `setupKeywords()` function. You also need to reimplement the `setName()` virtual since otherwise your parameters won't get renamed if the node does (see `srrc/procedure/nodes/select.cpp`, line 61 for example).

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +            return true;
Can simplify this:
```suggestion
        return forEachBranch_.prepare(procedureContext);
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +    return true;
```suggestion

    return true;
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +    return true;
```suggestion
    return forEachBranch_.finalise(procedureContext);
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.h
> +    // Whether to use only the current binned data of the histogram, rather than the accumulated average
```suggestion
    private:
    // Whether to use only the current binned data of the histogram, rather than the accumulated average
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +        return true;
Don't strictly need this one since we will fall through to the one at the end of the function after the loop completes.
```suggestion
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +            valueParameter_->setValue(data.value(index));
This loop is actually wrong - it's iterating over the actual values of the data, rather than the indices of the vectors (that would have needed `data.nPoints()`. Anyway, we can use our nice `zip` function here to iterate simultaneously over the two parts:
```suggestion
        for (const auto &&[x, value] : zip(data.xAxis(), data.values()))
        {
            xParameter_->setValue(x);
            valueParameter_->setValue(value);
```

2023-08-17 08:06 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
> +}
Need to create the parameters:
```suggestion

    xParameter_ = parameters_.emplace_back(std::make_shared<ExpressionVariable>("x"));
    valueParameter_ = parameters_.emplace_back(std::make_shared<ExpressionVariable>("value"));
}
```

2023-08-22 14:41 UTC, rprospero approved these changes
I'm approving this, but I've also included an improvement in the comments.  You can make those changes now or you can write an issue for it and we'll merge what we have.

2023-08-22 14:41 UTC, rprospero commented on src/procedure/nodes/iteratedata1d.h
> +    std::shared_ptr<const IntegerCollect1DProcedureNode> sourceIntegerData_;
We could make an abstract class `AbstractCollect1DProcedureNode` and have both `Collect1DProcedureNode` and `IntegerCollect1DProcedureNode` descend from it.  This would allow IterateData1D to have a single `sourceData_` pointer that could reference either type, depending on which concrete class it's pointing toward.  This would simplify a bunch of the logic in the prepare and execute functions.

2023-08-23 08:08 UTC, trisyoungs requested changes
Sorry - also just noticed that the new files don't conform to lowerCamelCase - the source files should be `iterateData1D.h` and `iterateData1D.cpp`.

2023-08-24 17:54 UTC, trisyoungs approved these changes
:+1:

2023-08-24 19:29 UTC, trisyoungs commented on src/procedure/nodes/iteratedata1d.cpp
@Danbr4d Still have the old files (before rename) included in the PR!

2023-08-29 13:37 UTC, merged