Just Tests
trisyoungs/duq pull request #1636
Opened 2023-08-16 08:17 UTC by trisyoungs

This PR aims to address the current mix of system and unit tests we have in our test suite, with the ultimate goals being:

- A consistent set of "just tests", whether they are unit, system, or somewhere in-between, organised in a single directory and run under a single testing framework.
- Refactoring all existing system tests, which more-or-less encompass running a small workflow in order to generate data, and then testing this data against "known correct" values, over `gtest`.
- Removal of keywords (e.g. `SampledVectorKeyword`, `SampledDoubleKeyword`) and modules (principally `DataTest`) which were added purely to facilitate system tests to be performed as a standard workflow.

The `DataTest` module actually has some utility as a well-formed user-facing module, but this functionality will be reinvented in new module(s) as part of #1620.

2023-08-16 08:54 UTC, jws-1 commented
I like it - looks like writing new system tests should be nice and easy in the future!

2023-08-16 09:12 UTC, rhinoella commented on unit/modules/avgMol/water.cpp
> +        EXPECT_NO_THROW(systemTest.setUp("../unit/modules/avgMol/water.txt"));
```suggestion
        ASSERT_NO_THROW(systemTest.setUp("../unit/modules/avgMol/water.txt"));
```
Maybe it is better to `assert` here as it doesn't make sense for the test to continue if dissolve isn't set up?

2023-08-16 09:15 UTC, rhinoella commented
All looks good!

2023-08-16 09:16 UTC, rhinoella approved these changes

2023-09-01 10:14 UTC, rprospero requested changes
I can't add a tag for this, but the `tests` preset in CMakePresets.json needs to be updated to the new `BUILD_TESTS` flag.  I'm taking a deeper look, but that needs handling before the PR can go in.

2023-09-01 10:14 UTC, rprospero commented on flake.nix
> +            patches = [ ];
```suggestion
```
Might as well drop the entire patches tag.

2023-09-01 10:15 UTC, jws-1 reviewed
I really, really like this piece of work! A few very minor comments to consider, from the small portion of code that I reviewed! One thing to note - only 67% of tests pass on my machine, due to: `Failed to open file 'full.txt' for reading` (which I think I recall you mentioning previously)..

2023-09-01 10:15 UTC, jws-1 commented on tests/testData.h
> +    // Test Data1D
```suggestion
    // Test Data3D
```

2023-09-01 10:15 UTC, jws-1 commented on tests/testData.h
> +        const SampledVector &data = optData->get();
Any reason not to use `auto` here?
```suggestion
        const auto &data = optData->get();
```

2023-09-01 10:15 UTC, jws-1 commented on tests/testData.h
> +        ASSERT_TRUE(at);
I can understand the intention here, but it might be clearer to explicitly compare to `nullptr` - although it's up to you, ultimately!
```suggestion
        ASSERT_TRUE(at != nullptr);
```

2023-09-01 10:15 UTC, jws-1 commented on tests/testData.h
> +        Messenger::print("Testing intramolecular interaction: {}...\n", termInfo);
Do we need this?
```suggestion
```

2023-09-01 13:29 UTC, trisyoungs commented on tests/testData.h
> +        Messenger::print("Testing intramolecular interaction: {}...\n", termInfo);
If the tests all pass, then "No", but if a single parameter fails the double comparison, for instance, tracking in which term it was is much easier if we print this out prior to the checks!

2023-09-01 13:30 UTC, trisyoungs commented on tests/testData.h
> +        ASSERT_TRUE(at);
Our standards document forbids doing this implicit conversion for `int`s, but not for (shared) pointers. I'd be inclined to keep this as-is, personally.

2023-09-04 09:00 UTC, rprospero approved these changes

2023-09-04 09:00 UTC, jws-1 approved these changes

2023-09-04 09:30 UTC, merged