Overview Tab
trisyoungs/duq pull request #1639
Opened 2023-08-16 15:58 UTC by jws-1

This PR implements an initial `OverviewTab`, which currently acts as a navigation tab among the `Forcefield`, `Species` and `Configuration` tabs. This tab inherits from `MainTab`, but is constructed from QML. The QML creates a pseudo-view through careful use of `Repeaters` and `Delegates` wrapped in a `ColumnLayout`. The view shows a `DissolveModel`.

Currently this tab is not very pretty (or that useful!), but it's been a good exercise in QML and QML-C++ inter-operation, and lays the foundations for future work regarding #88.

2023-08-25 19:36 UTC, trisyoungs reviewed
This is a great start - the QML implementation really does make it nice and easy to understand whats going on.

There's obviously a lot of future scope to think about here! Moving away from the HTML-style layout and using a compound widget sub-layout for instance, but of course that's all out of scope for this PR.  The point is that this clearly marks out the way forward to do all of that.

2023-08-25 19:36 UTC, trisyoungs commented on src/gui/models/configurationModel.cpp
> +            return QVariant::fromValue(rawData(index)->nAtoms());
Since we're making heavier use of the roles now it would be well worth introducing our own enum with value starting at `Qt::UserRole` in order to make intention clear and remove the magic numbers.

2023-08-25 19:36 UTC, trisyoungs commented on src/gui/models/dissolveModel.h
> +    Q_PROPERTY(const ConfigurationModel *configurations READ configurations NOTIFY configurationsChanged)
Again for purposes of clarity it feels like our return functions for the various models should include `Model` in the name - e.g. `configurationModel`. Otherwise, the casual "old school" reader of the code (i.e. me!) might interpret this as being the `std::vector` of current `Configuration`.s

2023-08-25 19:36 UTC, trisyoungs commented on src/gui/qml/Configuration.qml
A general point regarding naming - as our qml directory gets more and more populated we need to consider a directory heirarchy in order to separate things into, in the present example, and `overview/` directory rather than renaming this file to `ConfigurationOverview.qml` (which more accurately reflects what it is).

2023-08-25 19:36 UTC, trisyoungs commented on src/gui/qml/Species.qml
> +        const impropers = speciesData(speciesIndex, Qt.UserRole + 4);
Another new enumeration.

2023-09-04 11:10 UTC, rprospero requested changes
Most things look good.  I've got a couple of optional comments in there, but I do feel that we should clean up the passing of models and counts before we merge.

2023-09-04 11:10 UTC, rprospero commented on src/gui/models/atomTypeModel.cpp
> +
On the one hand, I hate this code.  The reset model calls should always wrap the changes to the model.  This sort of code is an indication that we're fighting the QML model, instead of working with it.

On the other hand, at the moment, we are *not* working with the QML model.  The rest of the GUI doesn't know about these models and will be making changes to the AtomTypes without sending any signals.  Eventually, we should get to the point where those are also properly modeled and everything that deals with AtomTypes will be passed a reference to the main AtomType model and we deal with proper method calls from there.  In the interim, this =reset= method *must* exist.

2023-09-04 11:10 UTC, rprospero commented on src/gui/models/configurationModel.h
> +    Q_ENUM(ConfigurationUserRole);
Good call on the enum here 👍

2023-09-04 11:10 UTC, rprospero commented on src/gui/overviewTabFuncs.cpp
> +    qmlRegisterType<ConfigurationModel>("Dissolve", 1, 0, "ConfigurationModel");
As we move toward more QML, we should probably create a single method that registers all of the QML types when the program first loads.  I'm not sure if this is in scope for this PR, but it should at least be tagged as an issue.

2023-09-04 11:10 UTC, rprospero commented on src/gui/qml/ForcefieldView.qml
Is this a load bearing empty file?  I've had encountered those before, but we might delete this if we don't need it.

2023-09-04 11:10 UTC, rprospero commented on src/gui/qml/overview/Angles.qml
> +    }
My temptation here is that we should pass in the `dissolveModel.masterAngleModel` and make the text

```qml
text: `Angles(${angleModel.rowCount()})`
```

This way, if we want to provide more angle information later on, we can simple edit the Angles file without needing to edit the calls sites.  This might also let us pull `nMasterAngles` out of the `DissolveModel` class and make it less of a [God Object Anti-Pattern](https://en.wikipedia.org/wiki/God_object).


All of the above as extends to the other Master terms and AtomTypes.

2023-09-04 11:10 UTC, rprospero commented on src/gui/qml/overview/Node.qml
I like having the separate widget for the node container 👍

2023-09-04 11:10 UTC, rprospero commented on src/gui/models/dissolveModel.h
> +    Q_PROPERTY(int nMasterImpropers READ nMasterImpropers NOTIFY modelsUpdated)
```suggestion
    Q_PROPERTY(AtomTypeModel *atomTypesModel READ atomTypesModel NOTIFY atomTypesChanged)
    // The Master Bond Model
    Q_PROPERTY(const MasterBondModel *masterBondsModel READ masterBondsModel NOTIFY mastersChanged)
    // The Master Angle Model
    Q_PROPERTY(const MasterAngleModel *masterAnglesModel READ masterAnglesModel NOTIFY mastersChanged)
    // The Master Torsion Model
    Q_PROPERTY(const MasterTorsionModel *masterTorsionsModel READ masterTorsionsModel NOTIFY mastersChanged)
    // The Master Improper Model
    Q_PROPERTY(const MasterImproperModel *masterImpropersModel READ masterImpropersModel NOTIFY mastersChanged)
```

I get into a discussion lower down on why we should get rid of the count properties.

2023-09-04 11:46 UTC, jws-1 commented on src/gui/qml/ForcefieldView.qml
Oops. That was leftover from one of the earlier iterations. I'll get rid of this.

2023-09-04 11:52 UTC, jws-1 commented on src/gui/overviewTabFuncs.cpp
> +    qmlRegisterType<ConfigurationModel>("Dissolve", 1, 0, "ConfigurationModel");
I agree with you - I'm also not too keen on it living inside this constructor.

2023-09-04 12:18 UTC, jws-1 commented on src/gui/qml/overview/Angles.qml
> +    }
I agree with this in general. The only problem I see, and this might be due to me doing something wrong elsewhere, is that the view doesn't update with new rows, etc, automatically.

2023-09-04 12:59 UTC, rprospero commented on src/gui/qml/overview/Angles.qml
> +    }
You're right about that.  What we'll need to do is add a `rowCount` *property* to the `MasterTermModel` so that the binding works correctly.  However, this is growing beyond the scope of the PR.  Just add an issue for this and assign it to me.  I'll mark the PR as ready to merge.

2023-09-04 13:12 UTC, rprospero approved these changes

2023-09-04 13:24 UTC, jws-1 commented on src/gui/models/atomTypeModel.cpp
> +
Yeah, I felt like I was cheating when I wrote this. However, the way things currently are written this is a necessity..

2023-09-04 14:21 UTC, merged