1620 Compare Module
trisyoungs/duq pull request #1646
Opened 2023-08-23 13:32 UTC by rhinoella

2023-08-23 21:19 UTC, trisyoungs reviewed
I may not be fully awake while going through this, but it feels kinda overkill for what we want to do, and I fear is dragging us away from just getting a working 1D comparison up and running correctly, with multiple datasets, which is what we really need.

Perhaps I'm mistaking your intent, but at present this feels like its written to be a catch-all class that can store multiple different dimensionalities of data (which we don't want) rather than something more akin to a templated class taking, for instance, the type and file format (`Data1D` and `Data1DImportFileFormat`) and which then has specialisations to handle the difficult parts that don't translate across dimensionalities (e.g. the fact that `Data1D` derives from a base class, and which complicates the search for internal data of that type).

2023-08-23 21:19 UTC, trisyoungs commented on src/io/import/dataBase.h
> +    // Import Data1D using current filename and format
```suggestion
    // Import data using current filename and format
```

2023-08-23 21:19 UTC, trisyoungs commented on src/io/import/dataBase.h
> +    // Import Data1D using supplied parser and current format
```suggestion
    // Import data using supplied parser and current format
```

2023-08-23 21:19 UTC, trisyoungs commented on src/keywords/dataSource.cpp
> +    // Once finished reading the arguements, add the data to the module
```suggestion
    // Once finished reading the arguments, add the data to the module
```

2023-08-23 21:19 UTC, trisyoungs commented on src/math/data1D.h
> +    std::string tag_{""};
Don't need to brace-initialise this since `std::string` is constructed empty.

2023-08-23 21:19 UTC, trisyoungs commented on src/keywords/dataSource.cpp
What's the benefit of having this code in the cpp file, and explicitly instantiating the necessary types, over having a pure header-only class (which is what it feels like it should be)?

2023-08-24 10:38 UTC, rhinoella commented
> I may not be fully awake while going through this, but it feels kinda overkill for what we want to do, and I fear is dragging us away from just getting a working 1D comparison up and running correctly, with multiple datasets, which is what we really need.
> 
> Perhaps I'm mistaking your intent, but at present this feels like its written to be a catch-all class that can store multiple different dimensionalities of data (which we don't want) rather than something more akin to a templated class taking, for instance, the type and file format (`Data1D` and `Data1DImportFileFormat`) and which then has specialisations to handle the difficult parts that don't translate across dimensionalities (e.g. the fact that `Data1D` derives from a base class, and which complicates the search for internal data of that type).

@trisyoungs The intent is to have a `DataSource` template class that can handle Data1D, 2D and 3D objects depending on what the type is specified as:

https://github.com/disorderedmaterials/dissolve/blob/713c3528a866636c2e900480d2dae601d2843f72/src/modules/compare/compare.cpp#L10C5-L18C5

 The specialisation (Data1D requiring a different search function) has to be handled in Compare.cpp, as it requires the `ModuleContext` object which is provided in the `Compare::process()` function. So the main function of DataSource is to accept a set of internal/external data (1D, 2D or 3D depending on what is specified), construct a vector of the relevant object (`Data1D`, `Data2D` or `Data3D`) and add it to the module's data through the module's `addData()` function that is passed into its constructor.

2023-08-24 16:03 UTC, trisyoungs commented
@rhinoella Because of the need to have the processing module data to search? Couldn't you just pass this in as a const reference when creating the keyword?

2023-08-24 16:12 UTC, rhinoella commented
@trisyoungs Unfortunately the `moduleContext` object is only known and constructed during runtime, when it is passed into the `Compare::process()` function during `Dissolve::iterate()`, so the keyword is constructed before the `moduleContext` object is created.

2023-08-24 16:29 UTC, trisyoungs commented
@rhinoella True true. Alas, module constructors used to get passed the main `Dissolve&` object, but no longer, and so you could have gotten the `GenericList` from there. Curses to this design!  I guess you'd better just work this up, focussing on the 1D case, and see where you get to.

2023-09-07 08:29 UTC, trisyoungs requested changes
A large handful of comments and suggestions, but overall I like this a lot (and I can follow it now!). We will need to get the (de)serialisation complete before this gets merged in.

2023-09-07 08:29 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +SerialisedValue DataSource::serialise() const { return {}; }
Something like this should work:
```suggestion
SerialisedValue DataSource::serialise() const
{
    Serialisedvalue result;
    if (dataSourceType_ == Internal)
    {
        result["internal"] = internalDataSource_;
    }
    else
    {
        result["external"] = externalDataSource_.get();
    }
    return result;
}
```

2023-09-07 08:29 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +void DataSource::deserialise(const SerialisedValue &node, const CoreData &data) {}
And here:
```suggestion
void DataSource::deserialise(const SerialisedValue &node, const CoreData &data)
{
    internalDataSource_ = toml::find_or<std::string>(node, "internal", "");
    if (internalDataSource_.isEmpty())
    {
        dataSourceType_ = External;
        externalDataSource_.get()->deserialise(toml::find(node, "external"), coreData);
    }
    else
    {
        dataSourceType_ = Internal;
    }
}
```

2023-09-07 08:29 UTC, trisyoungs commented on src/classes/dataSource.h
> +    bool serialise(LineParser &parser, std::string_view keywordName, std::string_view prefix) const;
Where's your normal `deserialise()` function?

2023-09-07 08:29 UTC, trisyoungs commented on src/classes/dataSource.h
> +
```suggestion
```

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +    // Return minimum number of arguments accepted
```suggestion
    public:
    // Return minimum number of arguments accepted
```

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +                // Import the data
```suggestion

                // Import the data
```

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +                                 : dataSourceB.template addData<DataType, DataFormat>(data, format);
Why the need for the inline `template` here?  This looks odd!

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +    void deserialise(const SerialisedValue &node, const CoreData &coreData) override {}
Need these!

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSourceBase.cpp
> +// Returns reference to module data
```suggestion

// Returns reference to module data
```

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +                dataCounter++;
I completely understand the need for the counter as-is, but there's probably a way to get rid of that by storing the data references in wrappers in a `std::vector` and using an iterator.

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +            // Serialise the first data source
```suggestion

            // Serialise the first data source
```

2023-09-07 08:29 UTC, trisyoungs commented on src/keywords/dataSource.h
> +            // Skip to next iteration if dataSourceB is undefined
```suggestion

            // Skip to next iteration if dataSourceB is undefined
```

2023-09-07 08:29 UTC, trisyoungs commented on src/math/dataBase.h
> +
```suggestion
```

2023-09-07 08:29 UTC, trisyoungs commented on src/math/dataBase.h
> +// Data Base
Perhaps a little more detail on what this class' purpose actually is here? Just a full line comment, really!

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/compare.h
> +using rangeErrorPair = std::pair<std::vector<Range>, std::vector<double>>;
I think by convention we make and `using` pseud-type fully upper camelcase.

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/process.cpp
> +
Bit of debugee output!
```suggestion
```

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/process.cpp
> +    int index;
```suggestion
    auto index = 0;
```

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/process.cpp
> +    for (auto &dataPair : dataSources_)
Wouldn't it be nicer to do this here?
```suggestion
    for (auto &[dataSourceA, dataSourceB] : dataSources_)
```

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/process.cpp
> +
```suggestion
```

2023-09-07 08:29 UTC, trisyoungs commented on src/modules/compare/process.cpp
> +Module::ExecutionResult CompareModule::process(ModuleContext &moduleContext)
Obviously this is written purely with a focus on 1D data for now, which is fine, but when we move forward to other dimensionalities it will be nice to do the bulk of high-level processing in this function (i.e. checking for dataset validity etc.) and then using templated functions to do the actual comparisons.

2023-09-07 09:21 UTC, rhinoella commented on src/keywords/dataSource.h
> +                                 : dataSourceB.template addData<DataType, DataFormat>(data, format);
It's required for the MacOS build to pass unfortunately! Its because addData is an overloaded function so the compiler wants us to be very specific.

2023-09-07 12:40 UTC, rhinoella commented on src/classes/dataSource.h
> +    bool serialise(LineParser &parser, std::string_view keywordName, std::string_view prefix) const;
It can't be done in the dataSource class because it doesn't know the `FileAndFormat` type of the data. The `bool serialise()` function is just a little helper for the keyword.

2023-09-07 13:48 UTC, rhinoella commented on src/modules/compare/process.cpp
> +    for (auto &dataPair : dataSources_)
I need the pointer to the `dataPair` as they are used as the key in the `dataSourcesErrors` map:
https://github.com/disorderedmaterials/dissolve/blob/00bd84c54c2a2223f8c26f563f9c4729b6311769/src/modules/compare/process.cpp#L26
https://github.com/disorderedmaterials/dissolve/blob/00bd84c54c2a2223f8c26f563f9c4729b6311769/src/modules/compare/process.cpp#L51
https://github.com/disorderedmaterials/dissolve/blob/00bd84c54c2a2223f8c26f563f9c4729b6311769/src/modules/compare/process.cpp#L54

2023-09-07 13:52 UTC, rhinoella commented
## Changes:
- `DataSource` no longer inherits from `Serialisable` as there is no good way to implement the TOML `deserialise` function, as `DataSource` does not know the `FileAndFormat` type of the data. The only way to do this is to have all the data file and formats inherrit from a new base class that specifies a virtual `importData` function
- TOML serialisation/deserialisation functions properly implemented
- Used a `std::queue` instead of a counter in `DataSourceKeyword`

2023-09-08 08:51 UTC, trisyoungs commented on src/classes/dataSource.h
> +        return data_.get() != nullptr ? true : false;
```suggestion
        return data_ != nullptr;
```

2023-09-08 08:51 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +    }
```suggestion
    }
    
    return result;
```

2023-09-14 09:59 UTC, rhinoella commented
### Changes

- Type definition for a Data classes' associated file and format is stored in the class. This improves type-safety (prevents someone from using a `Data2D` object with a` Data1DImportFileFormat`) and also means that the template class `DataSourceKeyword` only needs one template parameter- the data class
- `DataSource` class stores the Data object and Format object as an `std::variant` instead of a `std::unique_ptr` as this further improves type safety

### Note
Due to the removal of `unique_ptr`, the `DataBase` class (parent class for `Data1DBase`, `Data2DBase` and `Data3DBase`) can also be removed. I left it in anyways because it reduces code-repetition but please let me know if it should be removed.

2023-09-14 10:27 UTC, rprospero requested changes, later dismissed
Everything looks really good.  I've just included one small change to fix the Windows build.

2023-09-14 10:27 UTC, rprospero commented on src/classes/dataSource.h
> +    using Format = std::variant<Data1DImportFileFormat, Data2DImportFileFormat, Data3DImportFileFormat>;
Good call on using the type alias

2023-09-14 10:27 UTC, rprospero commented on src/classes/dataSource.cpp
> +                    auto optData = processingModuleData.search<const T>(internalDataSource_);
```suggestion
                [&](auto &data)
                {
                    // Locate target data from tag
                    auto optData = processingModuleData.search<const std::remove_reference<decltype(T)>>(internalDataSource_);
```

This removes the template on the lambda, which is illegal at the moment and breaking the Windows build.  You'll also need to `#include <type_traits` at the start of the file to use `std::remove:reference`.

2023-09-15 09:07 UTC, trisyoungs approved these changes
Looking really very nice indeed.   I have a bunch of formatting comments, but nothing more than that.

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +    if (dataSourceType_ == Internal)
```suggestion

    // For Internal data sources, try to locate the data now
    if (dataSourceType_ == Internal)
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +        {
I kind of dislike the way the comment breaks up the "flow" of the `if`/`else`, so perhaps move it inside?
```suggestion
        }
        else
        {
            // For other data types just visit the variant
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +    // Return whether or not variant contains value
```suggestion

    // Return whether or not variant contains value
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +// Function to add internal data
```suggestion
// Set internal data source
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +    else
```suggestion
    // For internal data sources just need to write the tag. Externals write the file and format
    if (dataSourceType_ == Internal)
    {
        if (!parser.writeLineF("'{}'\n", internalDataSource_))
            return false;
    }
    else
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.cpp
> +        return std::visit(
This is actually a really nice use of `variant`/`visit`!

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.h
> +
```suggestion
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.h
> +    public:
```suggestion
    public:
    // Data Source Types
    enum DataSourceType
    {
        Internal,
        External
    };
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.h
> +    // Function to add internal data
Don't really need to describe these functions as functions, so...
```suggestion
    // Source specified data (only required for internal data sources)
    bool sourceData(GenericList &processingModuleData);
    // Set internal data source
```

2023-09-15 09:07 UTC, trisyoungs commented on src/classes/dataSource.h
> +    // Returns the data of the requested type
```suggestion
    // Returns data in the requested type
```

2023-09-15 09:07 UTC, trisyoungs commented on src/keywords/dataSource.h
> +// Template arguments: data class (Data1D, Data2D ...), data import file format
```suggestion
// Keyword managing a DataSource
```

2023-09-15 09:07 UTC, trisyoungs commented on src/keywords/dataSource.h
> +            // If data is internal
```suggestion
            // Next parse depends on whether we have internal / external data
```

2023-09-15 09:07 UTC, trisyoungs commented on src/keywords/dataSource.h
> +            // If data is external
```suggestion
```

2023-09-20 10:21 UTC, merged