1620 Compare Module GUI Implementation
trisyoungs/duq pull request #1662
Opened 2023-09-07 15:29 UTC by rhinoella

GUI implementation for the Compare Module (#1646 )

2023-09-27 09:03 UTC, rhinoella commented
- [ ] Have the buttons separate Data1D, Data2D and Data3D data
- [ ] Have all the data in the Data1D category on the same graph but with different offsets

2023-10-10 10:12 UTC, trisyoungs requested changes
Looking good, but a strong suggestion on changes to the handling of the display logic.

2023-10-10 10:12 UTC, trisyoungs commented on src/modules/compare/compare.cpp
> +    keywords_.add<RangeVectorKeyword>("ErrorRanges", "Ranges over which to calculate RFactors", ranges_);
I think we should be more general in our description here - "RFactors" is quite specific to EPSR and, while that might be the desired metric for a lot of people, it's just "errors" really.

2023-10-10 10:12 UTC, trisyoungs commented on src/modules/compare/gui/compareWidget.h
> +    std::array<QPushButton *, 3> buttons_;
Not sure I like stashing the widget pointers in an array like this. See below for a different suggestion...

2023-10-10 10:12 UTC, trisyoungs commented on src/modules/compare/gui/compareWidgetFuncs.cpp
> +        if (index == 0)
Why can't we just do:
```suggestion
        if (ui_.Data1DButton->isChecked())
```
You can set the state of the 1D button to be checked in Designer and presumably they're in a button group, so everything should work you want.

2023-10-10 10:12 UTC, trisyoungs commented on src/modules/compare/gui/compareWidgetFuncs.cpp
> +    updateControls(ModuleWidget::RecreateRenderablesFlag);
Neater?
```suggestion
    if (checked)
    {
        updateControls(ModuleWidget::RecreateRenderablesFlag);
    }
```

2023-10-10 10:17 UTC, rhinoella commented on src/modules/compare/compare.cpp
> +    keywords_.add<RangeVectorKeyword>("ErrorRanges", "Ranges over which to calculate RFactors", ranges_);
Ah! I missed that, thanks!

2024-03-01 13:40 UTC, trisyoungs approved these changes
The end of a long journey!  Some small suggestions mostly on comments.

2024-03-01 13:40 UTC, trisyoungs commented on src/classes/dataSource.h
> +    // Function to source data
```suggestion
    // Obtain data from the relevant source
```

2024-03-01 13:40 UTC, trisyoungs commented on src/classes/dataSource.h
> +    // Returns data
```suggestion
    // Return the data
```

2024-03-01 13:40 UTC, trisyoungs commented on src/classes/dataSource.h
> +            dataName_ = externalDataSource_.filename().substr(externalDataSource_.filename().find_last_of("/\\") + 1);
Would it be better to just store the full filename path as `dataName_`, in case a user is trying to compare two datasets of the same name from, e.g., different simulations?

2024-03-01 13:40 UTC, trisyoungs commented on src/classes/dataSource.h
> +        }
Do we need to be so strict here? What if the user adds a new DataSource in the GUI but just leaves it empty for the time being and (for instance) disables the parent `CompareModule` so it doesn't run?  That's a valid simulation and we shouldn't complain about writing the file because the data source isn't quite set up properly.

2024-03-01 13:40 UTC, trisyoungs commented on src/classes/dataSource.h
> +        }
Also, you don't make the same check for the TOML version.

2024-03-01 13:40 UTC, trisyoungs commented on src/keywords/dataSource.h
> +    // Reference to module data
```suggestion
    // Vector of data source pairs
```

2024-03-01 13:40 UTC, trisyoungs commented on src/keywords/dataSource.h
> +    // Returns reference to module data
Return data source pairs

2024-03-01 13:40 UTC, trisyoungs commented on src/keywords/dataSourceBase.cpp
> +DataSourceKeywordBase::DataSourceKeywordBase() : KeywordBase(typeid(this)) {}
This feels redundant. Is it not enough to call the KeywordBase constructor from your template class?

2024-03-01 13:40 UTC, trisyoungs commented on src/modules/compare/gui/compareWidget.h
> +
```suggestion
```

2024-03-01 20:39 UTC, rhinoella commented on src/classes/dataSource.h
> +            dataName_ = externalDataSource_.filename().substr(externalDataSource_.filename().find_last_of("/\\") + 1);
Can do, but only concern is that the full path will take a lot of space on the graph legend

2024-03-01 20:42 UTC, rhinoella commented on src/keywords/dataSource.h
> +    // Returns reference to module data
```suggestion
    // Return data source pairs
```

2024-03-01 20:43 UTC, rhinoella commented on src/keywords/dataSourceBase.cpp
> +DataSourceKeywordBase::DataSourceKeywordBase() : KeywordBase(typeid(this)) {}
Having the DataSourceKeywordBase class is necessary for registerProducer() (It rejects the template class without the base)

2024-03-05 11:43 UTC, trisyoungs commented on src/classes/dataSource.h
> +        return "";
May be able to get away with a ternary one-liner here (but GH won't let me make a suggestion in line) provided the types match up:
```
return dataSourceType_ == External ? externalDataSource_.filename() : "";
```

2024-03-05 11:43 UTC, trisyoungs commented on src/keywords/dataSource.h
> +    std::string_view getBasename(std::string_view filename) const { return filename.substr(filename.find_last_of("/\\") + 1); }
:+1:

2024-03-05 15:22 UTC, merged