Windows docker setup
trisyoungs/duq pull request #1681
Opened 2023-10-26 11:13 UTC by RobBuchananCompPhys

2023-10-27 12:10 UTC, rprospero requested changes
A couple of bits of the documentation that might need some checking.

2023-10-27 12:10 UTC, rprospero commented on Dockerfile
> +RUN nix-env -iA nixpkgs.xorg.xauth nixpkgs.xorg.xorgserver
Are we sure that this line is required?  Since XMing acts as our server, I wouldn't think that we should need it on the guest.  Similar for xauth, since we never established authentication anyway.

2023-10-27 12:10 UTC, rprospero commented on web/docs/userguide/developers/docker.md
> +Docker build -t dissolve .
```suggestion
docker build -t dissolve .
```

I believe that docker has to be lower case to work in `git bash` and I thought that the other two shells were case sensitive, but I may be wrong on this point.

2023-10-27 12:10 UTC, rprospero commented on web/docs/userguide/developers/docker.md
> +Run `nixGLIntel ./build/bin/dissolve-gui` to start the software.
That command should fail, since we haven't actually built dissolve yet.  The user will first need to run

```shell
cmake --preset GUI-nix
cmake --build build
```

2023-10-27 14:11 UTC, RobBuchananCompPhys commented on web/docs/userguide/developers/docker.md
> +Docker build -t dissolve .
I can confirm that `Docker` works (for me atleast) with git bash, but happy to change to lowercase `docker` for generality.

2023-10-27 14:17 UTC, RobBuchananCompPhys commented on Dockerfile
> +RUN nix-env -iA nixpkgs.xorg.xauth nixpkgs.xorg.xorgserver
I tried this previously without those packages and the forwarding didn't seem to work but I'm having another look at it now.

2023-10-31 10:24 UTC, RobBuchananCompPhys commented on Dockerfile
> +RUN nix-env -iA nixpkgs.xorg.xauth nixpkgs.xorg.xorgserver
Looks like we didn't need that line

2023-10-31 10:33 UTC, rprospero approved these changes
One optional change to clean the code, but otherwise looks good.

2023-10-31 10:33 UTC, rprospero commented on scripts/setup.sh
> +"/root/.nix-profile/bin/nix" "develop" "--extra-experimental-features" "nix-command" "--extra-experimental-features" "flakes" "/dissolve#"
```suggestion
"/root/.nix-profile/bin/nix" "develop" "/dissolve#"
```
Since we added the nix-command and flakes features to nix.conf in line six of the docker file, we shouldn't need to specify them in the script.

2023-10-31 13:24 UTC, merged