atom types
trisyoungs/duq pull request #1713
Opened 2023-11-15 14:04 UTC by RobBuchananCompPhys

2023-12-05 09:28 UTC, rprospero requested changes

2023-12-05 09:28 UTC, rprospero commented on src/gui/models/atomTypeModel.h
> +    Q_PROPERTY(int rowCount READ rowCount NOTIFY modelsUpdated)
We notify on the `modelsUpdated` signal, but I don't see where we ever actually emit the signal, so I don't think that the row count will ever be updated.  What we might want to do is bind a slot to all of the [pre-existing](https://doc.qt.io/qt-6/qabstractitemmodel.html#signals) signals that get thrown when the model changes (e.g. `modelReset`, `rowsRemoved`) and then emit a `modelsUpdated` when any of those signals occur.

2023-12-05 12:07 UTC, rprospero commented on src/gui/qml/overview/OverviewTab.qml
> +    property MasterTorsionModel masterTorsionModel
I'm also getting an error message that none of these types have been registered with the QML.  This might be a good time to think about issue #1656

2023-12-08 09:04 UTC, RobBuchananCompPhys commented on src/gui/models/atomTypeModel.h
> +    Q_PROPERTY(int rowCount READ rowCount NOTIFY modelsUpdated)
I've written a class to take care of connected up all these signals since there are quite a few that could change due to the QAbstractItemModel and so it feels like it makes sense to avoid repeating for each model - let me know what you think.

2023-12-08 11:40 UTC, rprospero commented on src/gui/models/modelUpdater.h
> +    Q_Object
```suggestion
    Q_OBJECT
```

2023-12-08 11:40 UTC, rprospero commented on src/gui/models/modelUpdater.h
> +    Q_Object
The macro names are case sensitive

2023-12-08 12:10 UTC, rprospero commented on src/gui/models/modelUpdater.h
> +#include <QAbstractItemModel>
Make sure to include to the SPDX file header.  Also, the header file will need the once pragma to ensure it doesn't get double included.

2023-12-08 12:11 UTC, rprospero commented on src/gui/models/modelUpdater.cpp
> +#include "gui/models/modelUpdater.h"
SPDX file header

2023-12-08 12:51 UTC, rprospero commented on src/gui/models/atomTypeModel.h
>      explicit AtomTypeModel(const CoreData &coreData);
So this is a problem because there's some places where we need to assign the AtomTypeModel at Runtime.  I can't give you a simple patch for this, but you'll want to set this up so that AtomTypeModel can still use the default constructor.

I know that this may be considered sacriligeous, but it may be worth doing this with multiple inheritance instead of composition.  Having the classes inherit from ModelUpdater means that we can just call the `connectModelSignals` whenever it's convenient for the class at hand.  Note that this is just a theory - I'm happy to stick with composition if you can make it work.

2023-12-08 14:03 UTC, RobBuchananCompPhys commented on src/gui/models/atomTypeModel.h
>      explicit AtomTypeModel(const CoreData &coreData);
Ok, that's something I can have a go at. What is exactly the crux of of the problem, though? Is it that we have not assigned an instance of `modelUpdater` when it is required by the `Q_PROPERTY`?

2024-01-10 11:44 UTC, rprospero approved these changes

2024-01-10 11:44 UTC, merged