1425 Preamble text in options groups - Part 1
trisyoungs/duq pull request #1730
Opened 2023-11-28 09:10 UTC by trisyoungs

This PR lays the foundation to enable #1425 by refactoring the way we store and organise our keyword data. Previously, the `KeywordStore` class had a simple `std::vector` of `KeywordStoreData`, with each containing a pointer to a `KeywordBase` object and the section / group to use when displaying it in the GUI.  This disconnect between actual organisation and the data being organised meant that the hierarchical map of the intended layout had to be generated before being used, and required a bunch of objects such as `std::map<std::string,std::vector<std::pair<....` making the code a bit messy and hard to understand.

Here we take the approach of storing the keywords in a hierarchical class structure, introducing `KeywordStoreSection` and `KeywordStoreGroup` classes to contain the data and provide `find()` functions etc. This also leaves the door wide open for an easy implementation of #1425.

Works towards #1425.

2023-11-28 11:28 UTC, rprospero requested changes
There's one line which I'm pretty sure is a bug.  If I'm wrong about that, I'm happy for it to merge.

2023-11-28 11:28 UTC, rprospero commented on src/gui/keywordWidgets/widgetFuncs.cpp
> +            continue;
Am I misunderstanding the code or should that be == instead of != ?

2023-11-28 12:32 UTC, trisyoungs commented on src/gui/keywordWidgets/widgetFuncs.cpp
> +            continue;
Well, that's embarrassing! This should indeed be `==`.

2023-11-28 13:39 UTC, rhinoella requested changes
Fixes to messenger warnings and some small suggestions!

2023-11-28 13:39 UTC, rhinoella commented on src/gui/keywordWidgets/dialogFuncs.cpp
> +        Messenger::warn("There are {} keyword sections defined, but only one can be displayed. Tell the developer!\n");
```suggestion
        Messenger::warn("There are {} keyword sections defined, but only one can be displayed. Tell the developer!\n", keywordStore.sections().size());
```

2023-11-28 13:39 UTC, rhinoella commented on src/gui/moduleControlWidgetFuncs.cpp
>          b->setAutoExclusive(true);
Redundant code because these attributes are already set during the construction of the button in `KeywordsWidget::buttonForGroup()`

2023-11-28 13:39 UTC, rhinoella commented on src/gui/nodeControlWidgetFuncs.cpp
> +            Messenger::warn("There are {} keyword sections defined, but only one can be displayed. Tell the developer!\n");
```suggestion
            Messenger::warn("There are {} keyword sections defined, but only one can be displayed. Tell the developer!\n", node_->keywords().sections().size());
```

2023-11-28 13:39 UTC, rhinoella commented on src/keywords/organiser.cpp
> +}
```suggestion
KeywordStoreGroup &KeywordStoreSection::createGroup(std::string_view groupName,
                                                    std::string_view groupDescription = "")
{
    auto oldGroup = getGroup(groupName);
    return oldGroup ? *oldGroup : groups_.emplace_back(groupName, groupDescription);
}
```
A shorter way of possibly doing this

2023-11-28 13:39 UTC, rhinoella commented on src/gui/moduleControlWidgetFuncs.cpp
>      }
```suggestion
        if (!firstButton)
        {
            firstButton = b;
            firstButton->setChecked(true);
        }
    }
```

Better to put these together (remove the if statement after this)

2023-11-28 13:39 UTC, rhinoella commented on src/keywords/organiser.cpp
> +}
Doesn't this function make the `createGroup()` function kind of redundant? They are both essentially doing the same thing except that `createGroup()` allows for a description to be specified. Maybe it's better to remove the group creation responsibilities of this function.

2023-11-28 14:58 UTC, trisyoungs commented on src/gui/moduleControlWidgetFuncs.cpp
>          b->setAutoExclusive(true);
Nice!

2023-11-28 15:00 UTC, trisyoungs commented on src/gui/moduleControlWidgetFuncs.cpp
>      }
:+1:

2023-11-28 15:25 UTC, trisyoungs commented on src/keywords/organiser.cpp
> +}
You're absolutely right here.  This whole PR went through a lot of to-and-fro before getting to this point, so there are improvements to be made!

2023-11-28 16:08 UTC, rhinoella approved these changes

2023-11-29 10:53 UTC, rprospero approved these changes

2023-11-29 10:53 UTC, merged