1709 Enabled Buttons for Modules
trisyoungs/duq pull request #1732
Opened 2023-11-29 13:58 UTC by trisyoungs

This PR moves the `ModuleLayerModel` from `QAbstractListModel` to `QAbstractTableModel` with a view to removing the "floating" controls for the enabled/disabled state and frequency of individual modules in the list.

Below, the old style is on the left, with this PR moving us to the right (see that we now have the means to clearly indicate the module type as well).
![image](https://github.com/disorderedmaterials/dissolve/assets/11457350/215557df-ae66-42fd-8ef7-37ed936fd7a4)

Closes #1709.
Closes #1677 (or at least obfuscates it).

2023-11-29 14:50 UTC, rhinoella requested changes
One issue, everything else looks great!

2023-11-29 14:50 UTC, rhinoella commented on src/gui/models/moduleLayerModel.cpp
> +    return (data->hasFormat("application/dissolve.module.move") || data->hasFormat("application/dissolve.module.create"));
```suggestion
    return (data->hasFormat("application/dissolve.module.move") || data->hasFormat("application/dissolve.module.create"));
```

2023-11-30 09:26 UTC, trisyoungs commented on src/gui/models/moduleLayerModel.cpp
> +    return (data->hasFormat("application/dissolve.module.move") || data->hasFormat("application/dissolve.module.create"));
Ah - found a bit of my debugging I forgot to remove!

2023-11-30 09:45 UTC, rhinoella approved these changes

2023-11-30 09:48 UTC, trisyoungs commented
@rhinoella - Requested a re-review as I missed a couple of bits before!

2023-11-30 14:11 UTC, rhinoella approved these changes

2023-12-01 09:17 UTC, merged