display qml scale charges dialog
trisyoungs/duq pull request #1763
Opened 2024-01-16 11:57 UTC by RobBuchananCompPhys

2024-01-16 15:09 UTC, rprospero requested changes
Okay, I've made a bunch of comments, so I want to take a moment here to say that I really like what you've done here.  This is a great use of the model setup and the QML code is pretty clean.

Besides the individual comments that I've made (and which I'm more than willing to listen, if you disagree), there's one larger change that I would suggest.  Your model is very good, but a bunch of the work is still ultimately performed by the `DissolveWindow::on_SpeciesScaleChargesAction_triggered` function (which is the way it's always been).  I think it would be worth adding a function to the model where you pass in a reference/pointer to the species and it does all the scaling within the model.  That gives us a couple of advantages:

1. It's now possible (and recommended) two write a unit test to confirm that the model performs the correct scaling.
2. There's less code in the menu GUI, which should really only be for dispatch
3. When we replace the main GUI with QML, there's no concern that we won't translate the logic correctly

2024-01-16 15:09 UTC, rprospero commented on src/gui/models/scaleChargesDialogModel.cpp
> +void ScaleChargesDialogModel::setOption(int option)
`option` would probably be better as an ENUM. It would make the switch statement clearer as to its intent.

2024-01-16 15:09 UTC, rprospero commented on src/gui/qml/ScaleChargesDialog.qml
> +                text: "Enter the scaling factor to apply to all atoms / the target sum to determine scaling factor from"
```suggestion
                text: "Enter the scaling factor to apply to all atoms / the target sum to determine scaling factor from"
                wrapMode: Text.Wrap
```

We might be able to make the dialog smaller if the text could wrap.

2024-01-16 15:09 UTC, rprospero commented on src/gui/qml/ScaleChargesDialog.qml
> +import Dissolve
```suggestion
import Dissolve
import "widgets" as D
```

We should pull in our custom widgets to ensure that we maintain a consistent look across the application.

2024-01-16 15:09 UTC, rprospero commented on src/gui/qml/ScaleChargesDialog.qml
> +            Text {
Go ahead and use the `D.Text` widget here to keep our customisations.

2024-01-16 15:09 UTC, rprospero commented on src/gui/models/scaleChargesDialogModel.h
> +    bool scale_, scaleTo_;
If `option` is a enum, we might be able to replace both these bools with  single enum (e.g. `scale_direction_`).

2024-01-16 15:42 UTC, RobBuchananCompPhys commented on src/gui/models/scaleChargesDialogModel.cpp
> +void ScaleChargesDialogModel::setOption(int option)
Nice, yeah agreed on the clarity

2024-01-16 16:27 UTC, RobBuchananCompPhys commented on src/gui/qml/ScaleChargesDialog.qml
> +                text: "Enter the scaling factor to apply to all atoms / the target sum to determine scaling factor from"
agreed!

2024-01-17 10:39 UTC, trisyoungs requested changes
Looking good, and I think @rprospero makes a convincing case for moving the functionality into the model.

Have added some other comments, but notice that in the screengrab the buttons are aligned bottom-left in the dialog, when convention suggests bottom-right is the correct location.

2024-01-17 10:39 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +    double scaleFactor = scaleChargesDialog.model->value();
```suggestion
    auto scaleFactor = scaleChargesDialog.model->value();
```

2024-01-17 10:39 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +            double scaleTarget = scaleChargesDialog.model->value();
```suggestion
            auto scaleTarget = scaleChargesDialog.model->value();
```

2024-01-17 10:39 UTC, trisyoungs commented on src/gui/qml/ScaleChargesDialog.qml
> +                font.pixelSize: 12
Here we set `pixelSize`, but at the root of the `Page` we use `pointSize`, and neither value corresponds to the "standard" of `11` used in the old UI files!

2024-01-17 10:39 UTC, trisyoungs commented on src/gui/qml/ScaleChargesDialog.qml
> +                text: "Enter the scaling factor to apply to all atoms / the target sum to determine scaling factor from"
It kinda feels like there is some inherent bad UI design being highlighted by the label text here (and which is obviously not your fault @RobBuchananCompPhys since you're just porting it over!).  Essentially we have two functions "Scale" and "ScaleTo" which are trying to make use of a single spin box, hence the dual description in  the label. A simple pair of radio buttons would clear this up no end, and while requiring a separate spinbox for each option, one could then remove one of the buttons.

2024-01-17 13:06 UTC, RobBuchananCompPhys commented on src/gui/menu_species.cpp
> +            double scaleTarget = scaleChargesDialog.model->value();
Is there a particular reason why we should `auto` here? Not sure this will be necessary after merging this code into the model, since it is getting the value from within the model instance and it's definitely a double.

2024-01-17 13:07 UTC, RobBuchananCompPhys commented on src/gui/menu_species.cpp
> +    double scaleFactor = scaleChargesDialog.model->value();
Same as below

2024-01-17 13:24 UTC, rprospero commented on src/gui/menu_species.cpp
> +            double scaleTarget = scaleChargesDialog.model->value();
It's not that there's a particular reason to use `auto` as much as there is no particular reason *not* to use it.  In general, using `auto` is preferable when it's available because it makes it easier to change types elsewhere in the program without needing to update the types *everywhere*.  For example, if we later decide to change the type of `value` to some other custom class, then we would also need to update this line, adding noise to the eventual PR.  Making this an `auto` gives us the freedom to change the type of `value` as long as it continues to conform to the same interface.

This is known as Generic Programming and is what C++ has been moving toward (and away from Object Oriented Programming).  It's basically a type-safe approach to duck-typing and using `auto` where possible helps enable this workflow.

2024-01-17 13:45 UTC, RobBuchananCompPhys commented on src/gui/menu_species.cpp
> +            double scaleTarget = scaleChargesDialog.model->value();
Sounds like that's the way to go then - thanks for the explanation @rprospero!
While I was aware that `auto` can have advantages like seamlessly altering APIs, my take stemmed from the fact that the main consumer of this particular method was now going to be the model class itself (via the member function `setScale`), but I can see that the situation *might* still arise where we would want to specify a different return type for `value` without messing things up elsewhere.

2024-01-23 17:35 UTC, RobBuchananCompPhys commented
I've added a unit test for the model. This should be good to go.

One outstanding issue is that user manually resizing the dialog's window doesn't seem cause the contained UI components to adapt their size/positioning, or enforce a minimum size. (Perhaps I'm missing something @rprospero?) 

![scale_charges2](https://github.com/disorderedmaterials/dissolve/assets/106311829/0eed4449-1702-42c5-8632-4ac51794b9d5)

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/menu_species.cpp
> +        if (!scaled)
```suggestion
        if (!dialog.model->scaleCharges(species))
```

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.cpp
> +        double sum = 0.0;
```suggestion
        auto sum = 0.0;
```

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.cpp
> +        if (scaleTarget == 0.0)
Literal comparisons of doubles always makes me uneasy, even if `0.0` is pseudo-well-defined. Maybe we should do something like `if (fabs(scaleTarget) < 1.0e-6)`??

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.cpp
> +        }
Moving the error message dialog from `menu_species.cpp` into here, rather than returning `false` from `ScaleChargesDialogModel` to handle this specific failure, feels like a more solid and self-contained approach. This function can then just be `void`.

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.h
> +    double currentValue_ = 1.0;
```suggestion
    double currentValue_{1.0};
```

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.h
Even though this is a relatively simple header, ersonally I'd like to see a few more single-line comments etc. separating related parts and data, just so it's brutally obvious what everything is for.

2024-01-24 10:03 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.cpp
> +        }
Of course, this will break your unit test, so perhaps still return the `bool` for success but add a second argument `bool showDialogOnError = true` to the `scaleCharges` function so you can prevent the dialog being raised when testing, but still test for success?

2024-01-24 10:05 UTC, trisyoungs commented
The dialog looks really nice now - great work on the harmonisation of styles!  One small thing - the `Cancel` button should be leftmost rather than occupying the default "human click" position of bottom-right.

2024-01-24 11:43 UTC, RobBuchananCompPhys commented on src/gui/models/scaleChargesDialogModel.h
Sure thing!

2024-01-24 12:01 UTC, RobBuchananCompPhys commented on src/gui/models/scaleChargesDialogModel.cpp
> +        }
Yeah, I think it's best to go for one or the other, and I get the impression there is not much use returning a bool since the main work of the function is being done on the `*species` instance. In the test I will call the `void` method and then make a test on each atom to check the scaling is correct.

2024-01-24 12:02 UTC, RobBuchananCompPhys commented on src/gui/models/scaleChargesDialogModel.cpp
> +        }
I do like the idea of the parameter to variably display the error message for testing situations

2024-01-25 09:41 UTC, rprospero commented on src/gui/scaleChargesDialogFuncs.cpp
> +#include <QQuickWidget>
```suggestion
#include <QQuickWidget>
#include <QHBoxLayout>
```

Includes needed for resizing.

2024-01-25 09:41 UTC, rprospero commented on src/gui/scaleChargesDialogFuncs.cpp
> +    QQuickWidget *view = new QQuickWidget(QUrl("qrc:/dialogs/qml/ScaleChargesDialog.qml"), this);
```suggestion
    QQuickWidget *view = new QQuickWidget(QUrl("qrc:/dialogs/qml/ScaleChargesDialog.qml"), this);
    view-setResizeMode(QQuickWidget::SizeRootObjectToView)
```

Tell QML to perform a resize when `view` is resized.

2024-01-25 09:41 UTC, rprospero commented on src/gui/scaleChargesDialogFuncs.cpp
> +    QObject::connect(model, SIGNAL(acceptSelection()), this, SLOT(accept()));
```suggestion
    QObject::connect(model, SIGNAL(acceptSelection()), this, SLOT(accept()));
    
    QHBoxLayout *topLeftLayout = new QHBoxLayout;
    topLeftLayout->addWidget(view);
    setLayout(topLeftLayout);
```

Tell the old-style Qt dialog to update the size of the view object when the window is resized.

2024-01-25 17:07 UTC, rprospero approved these changes

2024-01-26 09:47 UTC, merged

2024-01-26 09:51 UTC, trisyoungs approved these changes
Excellent stuff.  Some small suggested corrections (more `auto` and a few other bits) but this is good to go.

2024-01-26 09:51 UTC, trisyoungs commented on src/gui/scaleChargesDialogFuncs.cpp
> +    QQuickWidget *view = new QQuickWidget(QUrl("qrc:/dialogs/qml/ScaleChargesDialog.qml"), this);
```suggestion
    auto view = new QQuickWidget(QUrl("qrc:/dialogs/qml/ScaleChargesDialog.qml"), this);
```

2024-01-26 09:51 UTC, trisyoungs commented on src/gui/scaleChargesDialogFuncs.cpp
> +    QHBoxLayout *topLeftLayout = new QHBoxLayout;
```suggestion
    auto topLeftLayout = new QHBoxLayout;
```

2024-01-26 09:51 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.cpp
> +bool ScaleChargesDialogModel::scaleCharges(Species *species, bool showDialogOnError = true)
```suggestion
bool ScaleChargesDialogModel::scaleCharges(Species *species, bool showDialogOnError)
```

2024-01-26 09:51 UTC, trisyoungs commented on src/gui/models/scaleChargesDialogModel.h
> +    bool scaleCharges(Species *, bool);
```suggestion
    bool scaleCharges(Species *species, bool showDialogOnError = true);
```