Modifier Oxygen Sites Module setup
trisyoungs/duq pull request #1793
Opened 2024-02-06 15:08 UTC by Danbr4d

A module to be able to determine the types of oxygen (bridging, non-bridging and free) that are attached to a modifier atom.

2024-02-06 15:45 UTC, trisyoungs commented on src/module/module.cpp
> +                                                                 {ModuleTypes::ModifierOSites, "ModifierOSites"},
This'll do for now.  If we think a bit beyond what we're interested in, specifically forgetting about things like "two NF neighbours means its a bridging oxygen", we have a module which is saying "For all sites A near to a site B, how many of site C are near to site B" - in our language "For all M sites near an O, how many NF are near to the O."

Still don't have a good name suggestion though! :smiley:

2024-02-13 14:23 UTC, trisyoungs requested changes
Quite a lot of comments from me here, but largely all that's needed is a bit of a sweep through renaming stuff for clarity.

Otherwise, it's looking good, and I think the `ModifierOSites` name is good to run with.

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/modifierOSites.cpp
> +                                        exportFileAndFormat2_, "EndExport");
Can't have spaces in the keyword name, and the `End***` keyword must match the name (i.e. be `EndKeywordName`). Also, the variables for the exportFileAndFormats could be named to more clearly represent what it is they are saving.

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/modifierOSites.h
> +    bool export_{false};
Don't think this is used anywhere?
```suggestion
```

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/modifierOSites.h
> +// Calculate ModifierOSites Module
```suggestion
// ModifierOSites Module
```

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    auto &processingData2 = moduleContext.dissolve().processingModuleData();
Don't need a second reference.
```suggestion
```

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    // Filter the oxygen sites into those surrounded by exactly two NF sites
```suggestion
    // Filter the oxygen sites into those surrounded by up to two NF sites
```

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    auto &&[BO2, neighbourMap2] = filter2.filterBySiteProximity(allOxygenSites.sites(), modifierDistanceRange_, 0, 99);
Again, a bit of renaming here to make the objects clearly state what they contain would help.  "filter2" could be `mFilter` (and the original "filter" could then be `oFilter`).  "BO2" could be "filteredMSites" for clarity (then "BO" -> "filteredOSites") and then "neighbourMap2" could be "mNeighbourO" (and "neighbourMap" can then be "oNeighbourNF").  That, I think, makes things a lot clearer.

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    // Retrieve storage for the Q-species histogram
Not Q-species anymore!

2024-02-13 14:23 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    // So, we can use this to determine the Q numbers for each NF by counting the number of times a NF site appears in the map.
Comment needs updating to reflect the new calculation.

2024-02-14 13:22 UTC, Danbr4d commented on src/modules/modifierOSites/process.cpp
> +    // So, we can use this to determine the Q numbers for each NF by counting the number of times a NF site appears in the map.
Still need to re-write this bit

2024-02-15 09:04 UTC, trisyoungs commented on src/modules/modifierOSites/modifierOSites.cpp
> +                                        exportFileAndFormatTotalOSites_, "EndExportTotalO-M");
Just suggestions for alternate keyword names:
```suggestion
    keywords_.add<FileAndFormatKeyword>("ExportModifierData", "File format and file name under which to save calculated M-O data",
                                        exportFileAndFormatOType_, "ExportModifierData");
    keywords_.add<FileAndFormatKeyword>("ExportOxygenTypes", "File format and file name under which to save calculated M-O data",
                                        exportFileAndFormatTotalOSites_, "ExportOxygenTypes");
```

2024-02-15 09:04 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    // So, we can use this to determine the Q numbers for each NF by counting the number of times a NF site appears in the map.
```suggestion
    // For each modifier site, bin the number of neighbour oxygens, then for each of those oxygen bin its type.
```

2024-02-15 09:04 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    }
Just to clarify the intent of the calculation here - we want to know:
1) The number of nearby oxygens around a given modifier site, regardless of what type of oxygen it is (F, BO, NBO). This is just the coordination number histogram of O around M within a distance r.
2) For those surrounding oxygens we bin the type ( == number of NF sites within range) - so this gives us the numbers of each type of O site (<= 2 NF sites) around all M, but will double-count (or more) O sites which are near to more than one M site.

It's 2) that I'm not entirely clear on - I guess I just don't quite understand how this is normalised to give a "quotable line in a paper", if you see what I mean.

2024-02-15 09:04 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    // Create the display data
```suggestion
    // Store the normalised data
```
But see comment above!

2024-02-15 09:04 UTC, trisyoungs commented on tests/data/dissolve/input/modifierOSites-test2.xyz
> +
```suggestion
```

2024-02-15 09:04 UTC, trisyoungs commented on tests/data/dissolve/input/modifierTotalOSites.dat
Is it really true that the test xyz system has only one type of O site in it?!?  I can see two "free" P-O floating about in there!

2024-02-15 15:34 UTC, Danbr4d commented on tests/data/dissolve/input/modifierTotalOSites.dat
The TotalOSites test is to count the number of oxygens that a M is bonded to so all M are bonded to 1 oxygen

2024-02-15 15:56 UTC, Danbr4d commented on src/modules/modifierOSites/process.cpp
> +    }
I guess it's more of a percentage bonds to oxygen rather than a percentage of modifier sites. So it would show out of for example 10 bonds to oxygen atoms 1 was to a free 6 to a non-bridging and 3 to a bridging. So it shows that the modifier atoms are forming more bonds with the non-bridging atoms.

2024-02-19 09:39 UTC, trisyoungs approved these changes

2024-03-12 16:28 UTC, rprospero approved these changes
Some *very* minor formatting suggestions, but, otherwise, everything is good.

2024-03-12 16:28 UTC, rprospero commented on src/modules/modifierOSites/process.cpp
> +    {
```suggestion
```
If without an else

2024-03-12 16:28 UTC, rprospero commented on src/modules/modifierOSites/process.cpp
> +    }
```suggestion
```

Same

2024-03-12 16:28 UTC, rprospero commented on src/modules/modifierOSites/process.cpp
> +    }
```suggestion
```

2024-03-12 16:28 UTC, rprospero commented on src/modules/modifierOSites/process.cpp
> +    {
```suggestion
```

Same

2024-03-12 16:28 UTC, rprospero commented on src/modules/modifierOSites/process.cpp
> +        {
```suggestion
```

Same

2024-03-12 23:28 UTC, merged