1791 Mugglify CIF Importer
trisyoungs/duq pull request #1799
Opened 2024-02-16 15:50 UTC by trisyoungs

### Follows #1792 - Do not merge until #1792 is resolved

This PR performs a significant refactoring on the `CIFImportDialog`, turning it from a wizard into a fully-featured single-page dialog. Aside from, IMHO, a better UX, a significant secondary reason was the desire to streamline the underlying CIF generation and move away from doing the full, multi-stage generation every time a parameter was changed.

In other news, we also remove the local `CoreData` object and just go for local instances of the necessary (temporary) objects. A few bug fixes also along the way. Lovely.

Closes #1791.

2024-02-18 12:40 UTC, jws-1 commented
I see this is not ready for review yet, but just wanted to chime in and say I like the new look of things! A single page dialog is definitely the way to go (I got very fed up of the wizard when I was working on this stuff before!).

2024-02-18 15:40 UTC, trisyoungs commented
Yeah, I think my view on wizards has changed to the polar opposite now - can't stand em!  Particularly in the case of the CIF import, it felt like didn't give the users or the developers the best view on things.

2024-02-19 11:22 UTC, rhinoella commented on src/gui/menu_species.cpp
> +            ui_.MainTabs->setCurrentTab(dissolve_.coreData().species().back().get());
```suggestion
            ui_.MainTabs->setCurrentTab(sp);
```

2024-02-19 12:58 UTC, rhinoella requested changes
Looks good, minor comments.

2024-02-19 12:58 UTC, rhinoella commented on src/gui/importCIFDialog.cpp
Currently the MoietyNETARemoveFragmentsCheck and the MoietyNETARemovalEdit are disabled, I am assuming here is where they should be enabled.

```suggestion

ui_.MoietyNETARemovalEdit->setEnabled(checked);
ui_.MoietyNETARemoveFragmentsCheck->setEnabled(checked);

```

2024-02-19 12:58 UTC, rhinoella commented on src/gui/importCIFDialog.cpp
> +        cifHandler_.getTagString("_journal_page_first").value_or("???"))));
Personally, the question marks feel a bit aggressive, I think leaving it blank would look more professional.

2024-02-19 12:58 UTC, rhinoella commented on src/gui/importCIFDialog.cpp
> +    updateWidgets();
```suggestion

```

2024-02-19 12:58 UTC, rhinoella commented on src/gui/importCIFDialog.cpp
> +    updateWidgets();
Could also just change to:

```
cifHandler_.setUseCIFBondingDefinitions(checked);
updateWidgets();
```

And remove if statement

2024-02-19 15:10 UTC, trisyoungs commented on src/gui/importCIFDialog.cpp
Actually, the logic to enable/disable those controls based on the state of `ui_.MoietyNETARemoveCheck` is captured in the UI file itself with signals/slots/

2024-02-19 15:12 UTC, trisyoungs commented on src/gui/importCIFDialog.cpp
> +        cifHandler_.getTagString("_journal_page_first").value_or("???"))));
Agreed, but I'll switch to `N/A`.

2024-02-19 15:14 UTC, trisyoungs commented on src/gui/importCIFDialog.cpp
Oh, and which I see now somehow don't work.....

2024-02-19 15:20 UTC, trisyoungs commented on src/gui/importCIFDialog.cpp
> +    updateWidgets();
Best not to since these callbacks on the radio buttons should only ever run if the radio has been checked as the  companion radio button represents the other state choice (`false`).

2024-02-20 13:04 UTC, rhinoella approved these changes
Looks good!

2024-02-21 09:57 UTC, merged