OSites Bond Lengths
trisyoungs/duq pull request #1817
Opened 2024-03-13 11:58 UTC by Danbr4d

Added in feature to calculate the NF-O bond lengths for different O sites (BO and NBO)

2024-03-14 09:59 UTC, trisyoungs reviewed
What you've written here is a bit of a mixture of two different ways of doing things. What you have gone for is a straight "calculate the averages" approach - i.e. take all the M-O distances and bin them to get an average.  However, you're using a `Histogram1D` to do it so what you're actually getting is a proper distribution of values, rather than a single average.  When you come to call `value(1)` to get the value to display in the GUI, what you're actually getting is the second (because we're zero-indexed) value of the distance histogram you've calculated, rather than the average value for the "1" bin (which would need you to use an `IntegerHistogram1D` instead.

I think the most fully-rounded approach would be to calculate the individual full histograms for singly, double, and "other" oxygen types to get the distance distributions, plot those in the GUI, and offer up the average value as well as (if you want to get really fancy) a function fitted to the curve.  For the latter most of the infrastructure already exists in the `Fit1DProcedureNode`, and that would be nice to move over to the new analysis framework.

2024-03-14 09:59 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +            histAB.bin(targetConfiguration_->box()->minimumDistance(siteM->origin(), oSite->origin()));
As written this gives us the M-O distances over all types of oxygen - i.e. the "simple" RDF that you could just calculate with `SiteRDF`.  Do we not want the RDFs of M-O for each type of O (1 modifier neighbour, 2, more) separately?

2024-03-14 09:59 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +        histAB.initialise(distanceRange_.minimum(), distanceRange_.maximum(), 0.05);
In the comment for this `realiseIf` you call it `rNFO` (shouldn't it be `rMO`?) but call the variable `histAB` - why not follow that naming scheme and call it `histNFO` (or `histMO`) for clarity?

2024-03-14 09:59 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    histogramNormaliser.normaliseTo();
I'd move all this up near to the `Data1D dataNormalisedHisto` so it's all together.

2024-03-14 09:59 UTC, trisyoungs commented on src/modules/modifierOSites/gui/modifierOSitesWidgetFuncs.cpp
> +
This I guess is where your crash is happening - what I think is going on is that the `setText()` expects a `SampledDouble` while the `value()` function returns a `double`.  There is a defined conversion from `double` to `SampledDouble`, so this should work, but I guess there's a bug deep in there somewhere.  Anyhoo, this is probably irrelevant (see main comment).

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +    if (status3 == GenericItem::ItemStatus::Created)
You might want to consider doing a sweep and renaming these status variables to something more specific since there are now a lot of them. For example here it could simply be `histMFOstatus`.

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +                case 0:
Just for my own sanity here - when we are calling these "free oxygens" / FO what we really mean is that they are not next to any network former atoms? Is that right?

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +
If you can construct an array of references to these histograms with something like this then your analysis loop becomes really nice and simple:
```
std::vector<std::reference_wrapper<Histogram1D>> histogramsMO = { histMFO, histMNBO, histMBO, histMOtherO };
```
Haven't tried this so it may need some tweaking, but then later on......

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +            }
...you can just do this!
```suggestion
            histogramsMO[std::min(neighbourMap[oSite].size(), 3)].bin(targetConfiguration_->box()->minimumDistance(siteM->origin(), oSite->origin()));
```

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/process.cpp
> +            }
Honestly, we shouldn't be having to use a separate output FileAndFormat for each of these graphs.  What Dissolve probably needs is a file and format that can output multiple Data1D of the same size into the same file at once, but that's an issue for another day.

2024-03-18 13:54 UTC, trisyoungs commented on src/modules/modifierOSites/gui/modifierOSitesWidget.h
> +    DataViewer *mOtherOBondLengthGraph_;
Don't you think it would be better to plot all of these data on the same graph?

2024-03-18 14:46 UTC, Danbr4d commented on src/modules/modifierOSites/process.cpp
> +                case 0:
Yes that's right

2024-03-18 16:22 UTC, Danbr4d commented on src/modules/modifierOSites/gui/modifierOSitesWidget.h
> +    DataViewer *mOtherOBondLengthGraph_;
To do this I had to get rid of the `if(renderables().empty())` to be able to actually plot on the same graph but now my legend looks like this, any reasons? 
![image](https://github.com/disorderedmaterials/dissolve/assets/115464393/de97bc50-f14b-4e8b-8078-ec1daee341cf)

2024-04-08 07:55 UTC, trisyoungs requested changes
Looking good, but a couple of small things in the comments.  Also I noticed that the keyword name for the modifier sites is still "SiteA", while the other two ("BondingOxygen" and "NetworkFormer") have more descriptive names.

2024-04-08 07:55 UTC, trisyoungs commented on tests/data/dissolve/input/modifierOSites-test2.xyz
> +P            -5.5.0000    0.000000   -16.000000     0.000000
```suggestion
P            -5.500000    0.000000   -16.000000     0.000000
```

2024-04-08 07:55 UTC, trisyoungs commented on tests/modules/modifierOSites.cpp
> +    ASSERT_NEAR(mBOdata.value(40), 0.66666666666, 1e-8);
Rather than a lot of "magic array accessing" (for want of a better phrase!)  I think I'd rather see a straight comparison of `Data1D` objects.  You can export these from your module and add them as test data - as long as you've validated the contents by eye once you've exported them, this is fine.

2024-04-08 11:00 UTC, trisyoungs approved these changes

2024-04-15 14:24 UTC, rprospero approved these changes

2024-04-15 14:25 UTC, merged