1816 Rename Data Normaliser
trisyoungs/duq pull request #1820
Opened 2024-03-17 12:54 UTC by jws-1

Small PR renaming `DataNormaliserND` to `DataOperatorND` (this also applies to the subclasses), also adds some additional comments to the relevant classes for clarity.

Closes #1816.

2024-03-19 11:14 UTC, trisyoungs requested changes

2024-03-19 11:14 UTC, trisyoungs commented on src/analyser/dataOperator3D.cpp
>      Messenger::warn("Normalisation function not implemented for 3D data.");
```suggestion
    Messenger::warn("Data operate() function not implemented for 3D data.");
```

2024-03-19 11:14 UTC, trisyoungs commented on src/analyser/dataOperatorBase.h
> +    virtual void normaliseTo(double value = 1.0, bool absolute = true) = 0;
For ultraclarity I think I would suggest renaming this one:
```suggestion
    // Normalise the sum of the target data to a given value
    virtual void normaliseSumTo(double value = 1.0, bool absolute = true) = 0;
```

2024-03-19 11:14 UTC, trisyoungs commented on src/analyser/dataOperator1D.cpp
> +        values.at(i) = operateFunction(xs[i], targetData_.error(i), values.at(i));
`targetData_.error(i)`?

2024-03-26 09:19 UTC, trisyoungs approved these changes
Looks good.  Just a couple comments on naming.

2024-03-26 09:19 UTC, trisyoungs commented on src/analyser/dataOperator1D.cpp
> +void DataOperator1D::operate(OperateFunction1D operateFunction)
I think just calling the function argument `operator` feels a lot cleaner:
```suggestion
void DataOperator1D::operate(OperateFunction1D operator)
```

2024-03-26 09:19 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +            auto normType = module->keywords().getEnumeration<StructureFactors::NormalisationType>("normaliseTo");
Bit of aggressive search/replacing!
```suggestion
            auto normType = module->keywords().getEnumeration<StructureFactors::NormalisationType>("NormaliseTo");
```

2024-03-26 09:19 UTC, trisyoungs commented on src/modules/epsr/process.cpp
> +            auto normType = module->keywords().getEnumeration<StructureFactors::NormalisationType>("normaliseTo");
```suggestion
            auto normType = module->keywords().getEnumeration<StructureFactors::NormalisationType>("NormaliseTo");
```

2024-03-26 12:51 UTC, jws-1 commented on src/modules/epsr/process.cpp
> +            auto normType = module->keywords().getEnumeration<StructureFactors::NormalisationType>("normaliseTo");
Agh!...

2024-04-05 13:08 UTC, trisyoungs commented
@jws-1 The suggestion to rename to `operator` may be the worst code suggestion I've ever made - sorry about that!  Silly reserved words....

2024-04-05 13:51 UTC, jws-1 commented
> @jws-1 The suggestion to rename to `operator` may be the worst code suggestion I've ever made - sorry about that! Silly reserved words....

Hah. I changed it and then forgot about it! I'll revert.

2024-04-05 15:06 UTC, merged