feat: Remove TemperatureProcedureNode and set temperature through toolbutton
trisyoungs/duq pull request #1855
Opened 2024-04-15 10:25 UTC by rhinoella

Removes depreciated `TemperatureProcedureNode` and instead sets temperature through a toolbutton in the configuration tab.

2024-04-15 14:10 UTC, trisyoungs requested changes

2024-04-15 14:10 UTC, trisyoungs commented on src/gui/configurationTab.cpp
> +
This duplicates code from `DissolveWindow` so I'd suggest just connecting the `clicked` signal from `TemperatureToolButton` to `DissolveWindow::on_ConfigurationAdjustTemperatureAction_triggered` in the tab's constructor.

The modified status as well as the update are then handled consistently, and you can revert your addition of the `updateTemperatureLabel` function.

2024-04-15 14:10 UTC, trisyoungs commented on src/procedure/nodes/CMakeLists.txt
> -  temperature.cpp
We shouldn't remove the `TemperatureNode` completely at this point since this will break every single input file from versions < 1.5. Your PR stops it from being added to new simulations, which is a sensible first step, and we can remove it entirely in v2.0.

2024-04-15 14:10 UTC, trisyoungs commented on src/procedure/nodes/registry.cpp
> -                                               "Build");
Keep!

2024-04-15 18:42 UTC, rhinoella commented on src/gui/configurationTab.cpp
> +
QT doesn't like it when I tried to connect() the button to the `DissolveWindow` slot, so I kept the `ConfigurationTab::on_TemperatureToolButton_clicked` just call the slot manually.

2024-04-15 20:52 UTC, trisyoungs requested changes
Sorry - sent you a message on Teams expressing how bad I got this wrong. Made way more work for you than it should have been!

I just tried the signal connection, and for me adding this in the `ConfigurationTab` constructor worked just fine, and lets you simplify your PR quite a bit:
```
connect(ui_.TemperatureToolButton, SIGNAL(clicked(bool)), dissolveWindow_, SLOT(on_ConfigurationAdjustTemperatureAction_triggered(bool)));
```

2024-04-15 20:52 UTC, trisyoungs commented on examples/argon/input.txt
> +
Need to remove the keyword (this is the deprecated part) and reintroduce the node.

2024-04-16 09:20 UTC, rhinoella commented
@trisyoungs Please double-check the changes to the Sillica example, I am not entirely sure if the node is appropriate for this example.

2024-04-16 12:43 UTC, trisyoungs requested changes
Need a change to the silica example. Did you see my suggestion for connecting the signal as well?

2024-04-16 12:43 UTC, trisyoungs commented on web/docs/examples/silica/step5.md
> +{{< action type="mouse" >}}Click {{< gui-button text="Generate" icon="repeat" >}} to update the configuration.{{< /action >}}
This would destroy the configuration we already have - regenerating the configuration loses all the simulation we've done on it to date. So here is a perfect place to point the user to the button on the configuration tab *or* the main menu item.

2024-04-16 12:43 UTC, trisyoungs commented on web/docs/examples/argon/step3.md
> +{{< tip >}}Make sure to click {{< gui-button text="Generate" icon="repeat" >}} to save your changes. You can recreate a configuration at any time by clicking the {{< gui-button text="Generate" icon="
```suggestion
{{< tip >}}Make sure to click {{< gui-button text="Generate" icon="repeat" >}} to update the configuration with any changes you're made to the generator procedure. You can recreate a configuration at any time by clicking the {{< gui-button text="Generate" icon="repeat" >}} button, but bear in mind that other quantities calculated by modules may also need to be cleared. Remove all of this data to begin a 'clean' run with the **Clear Module Data** option in the **Simulation** menu.{{< /tip >}}
```

2024-04-16 14:03 UTC, trisyoungs approved these changes
:+1:

2024-04-16 17:24 UTC, merged