refactor: Fully QML GUI as separate target executable
trisyoungs/duq pull request #1894
Opened 2024-05-10 15:30 UTC by RobBuchananCompPhys

2024-05-13 10:04 UTC, rprospero requested changes
I haven't had a chance to take a good look at the actual C++ (I'll do that after lunch), but this rewrite is a great opportunity to drop a ton of link time dependencies that we won't really need.  I've gone through and pruned it down a bit, with some suggestions on how to do a little more.

2024-05-13 10:04 UTC, rprospero commented on src/dissolve-gui-qml.cpp
> +#include "gui/gui.h"
```suggestion
#include "gui/models/dissolveModel.h"
```

We don't want to include the entire GUI, but only the main model.  I mention this mostly because it enables us to skip linking against some dependencies that we would like to escape.

2024-05-13 10:04 UTC, rprospero commented on CMakeLists.txt
> +            ${Qt6OpenGLWidgets_INCLUDE_DIRS}
```suggestion
            ${Qt6Core_INCLUDE_DIRS}
            ${Qt6Gui_INCLUDE_DIRS}
```

The new GUI hopefully shouldn't need most of these libraries, and currently works without them.

2024-05-13 10:04 UTC, rprospero commented on CMakeLists.txt
> +            gui
```suggestion
            # Main gui libs
            gui-qml
```

Only need to link against out new gui-qml library.  It includes the inner libraries that we need (i.e. `models`).

2024-05-13 10:04 UTC, rprospero commented on CMakeLists.txt
> +            ${THREADING_LINK_LIBS}
```suggestion
            Qt6::Qml
            ${CORE_LINK_LIBS}
            ${THREADING_LINK_LIBS}
```

Cutting down dependencies again

2024-05-13 10:04 UTC, rprospero commented on src/gui-qml/CMakeLists.txt
> +  resources.qrc
```suggestion
  # Types for QML access
  ../gui/types.cpp
```

Two bits here.  First, if we link against the resources here, then we get a duplicate linkage error when we link against it again when we define the main executable in the primary CMake file.  Since we *must* link against it in the primary CMake file, we shouldn't link against it here.

The second issue that we run into is that the only file, besides the models, that we need from the main gui is the `types.cpp` file that enables accessing our custom types from QML.  I've done an ugly, direct linkage here, but I'm wondering if `types.cpp` should just be in the `models` folder and linked into that library.

2024-05-13 10:04 UTC, rprospero commented on src/gui-qml/CMakeLists.txt
> +          Qt6::OpenGLWidgets
```suggestion
```

Dropping more dependencies

2024-05-13 10:04 UTC, rprospero commented on src/gui-qml/CMakeLists.txt
> +          Qt6::QmlModels
```suggestion
```

Dropping

2024-05-13 10:09 UTC, RobBuchananCompPhys commented on src/dissolve-gui-qml.cpp
> +#include "gui/gui.h"
Makes sense!

2024-05-14 09:39 UTC, trisyoungs reviewed
Tested and working well on Linux.  :+1:

2024-05-14 11:50 UTC, RobBuchananCompPhys commented
> Tested and working well on Linux. 👍

Great, thanks for looking into it. @rprospero do we need to look at restoring some of those dependencies to fix the macos build?

2024-05-14 17:03 UTC, rprospero commented
Just a record of where I'm at on this.

1. For some reason, on the Mac build, and only the Mac build, the QML gui depends on our `render` target.
2. The `render` target depends on FTGL.
3. The `render` target also depends on the `StockColours` class, which is in the `gui` target.
4. Having the QML GUI depend on `gui` means brining in *all* of the other dependencies.

There's three possible routes forward from here

1. Try and remove the Apple dependency on the `render` target.
2. Split the classes required by `render` out of `gui` and into a separate target.
3. Abandon all hope and just link all the dependencies back into the QML gui.

I've listed the options in the order that I will attempt them.

2024-05-15 08:16 UTC, trisyoungs commented
@rprospero I don't think the dependency issue with `StockColours` can be easily solved, and actually just represents the tip of a rather large and annoying iceberg. Almost every module-related widget, and most of our `MainTab`-derived ones, use a `Viewer` of some kind which brings in the `render` dependency. So, I don't see a clean way of detaching the current GUI from these dependencies for plugging into the new QML one.  Perhaps the beset route is to not link to the current `gui` dependency _at all_ in the new QML frontend, and incrementally build it back up from scratch.  This provides an opportunity to overhaul the workflows that we currently have in place, and should encompass our move to "Workflow 2.0" at the same time, IMO. A lot of work to be sure, but this at least moves the focus of our efforts into a single reimagining of the GUI, rather than worrying about reimplementing the old one and then changing it anyway.

2024-05-17 08:50 UTC, trisyoungs approved these changes
Looks like an excellent starting point.

2024-05-17 14:47 UTC, rprospero approved these changes

2024-05-17 14:47 UTC, rprospero commented on src/dissolve-gui-qml.cpp
> +        // loadSuccessful = dissolveWindow.loadInputFile(options.inputFile().value());
Since we've commented out the actual action, this if statement will act on the next statement.  Granted, that is also another conditional that tests the same condition, but it might be better to comment out or remove the condition.

2024-05-17 14:47 UTC, rprospero commented on src/dissolve-gui-qml.cpp
> +    Messenger::print("For more details read the GPL at <http://www.gnu.org/copyleft/gpl.html>.\n");
It might be useful to put this boilerplate for in a method on the `Dissolve` class.  You could pass in the program name and it could do this generic setup.  Granted, we don't have to do it on this PR, but it might be worth flagging the issue.

2024-05-17 14:47 UTC, merged

2024-05-17 19:45 UTC, trisyoungs commented on src/dissolve-gui-qml.cpp
> +        // loadSuccessful = dissolveWindow.loadInputFile(options.inputFile().value());
We'll need it eventually probably, so I'd vote for commenting the condition out.