Feat/voxel density module
trisyoungs/duq pull request #1949
Opened 2024-06-27 08:44 UTC by RobBuchananCompPhys

2024-07-17 10:21 UTC, rprospero requested changes
Obviously the formatting issues need to be taken care of, but everything else looks really good

2024-07-17 10:21 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +        }
```suggestion

        double value;
        switch(targetProperty_)
        {
            case TargetPropertyType::Mass: 
                value = AtomicMass::mass(atomicNumber);
                break;
            case TargetPropertyType::AtomicNumber: 
                value = atomicNumber;
                break;
            case TargetPropertyType::ScatteringLengthDensity:
                value = Sears91::boundCoherent(Sears91::naturalIsotope(atomicNumber));
            }
            default:
            {
                throw(std::runtime_error(
                fmt::format("'{}' not a valid property.\n", targetProperty_)));
            }
        }
        density.addPoint(
            (double)x*numPoints_, 
            (double)y*numPoints_, 
            (double)z*numPoints_,
            value);
                ); 
```

I thought it might be a bit easier to read if the switch statement merely selected a value and then the same code was used to add every type of point.

More concerning is that your `switch` doesn't seem to have any `break` statements.  I would have expected that any call to this function would immediately throw and exception as the various cases fall through each other to the final, `default` case.

This brings up the larger point that this module needs a unit test to confirm that it works properly.

2024-07-17 13:44 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +        }
Thank you for pointing out the lack of `break`s, honest mistake.

What would be a good test case for this?

2024-07-18 12:06 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +                // throw(std::runtime_error(fmt::format("'{}' not a valid property.\n", targetProperty_)));
I noticed that you commented out the `throw` statement here.  Honestly, I liked having it there.  We have `throw` statements in the NeutronSQ and XraySQ serving the similar purpose of checking for invalid enums.  Is there a reason that you took it out?

2024-07-18 12:25 UTC, rprospero commented
@RobBuchananCompPhys  You'd made a comment asking about what could serve as a good test case.  The first idea that comes to mind is as follows:

Generate a box with a million Helium atoms in it and get the 10x10x10 voxel density.  The first test would be going through the voxel values and ensuring that the individual voxel values add up to a million.  The next part is loops through the individual values and checking for outliers.  If more than fifty of the values are outside 1000 ± 70 or more than four values are outside of 1000 ± 100, then something has gone wrong.

There's probably an even better test to be made by *not* distributing the helium atoms evenly, but the above would be a good start.

2024-07-18 13:13 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +                // throw(std::runtime_error(fmt::format("'{}' not a valid property.\n", targetProperty_)));
It was causing complilation to fail, I'll try again with it uncommented

2024-07-19 07:56 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +                // throw(std::runtime_error(fmt::format("'{}' not a valid property.\n", targetProperty_)));
Turns out the enum value was not formattable, casting it to an `int` works

2024-07-26 13:09 UTC, rprospero reviewed
Some suggestions and questions.  I think that we're getting closer.

2024-07-26 13:09 UTC, rprospero commented on src/math/data1D.cpp
> +
```suggestion
// Return number of non-zero values present in whole dataset
std::vector<std::tuple<double, double>> Data1D::nNonZeroValues() const
{
    std::vector<std::tuple<double, double>> pairs;
    auto xys = zip(x_, values_);
    
    std::copy_if(std::execution::par_unseq, xys.begin(), xys.end(), std::back_inserter(pairs), [](const auto &val) { return std::get<1>(val) > 0; });
    return pairs;
}
```

Using zip keeps the x_ and values_ terms cleanly together without needing to keep track of a mutable iterator, which suddenly means that we can do it all in parallel.

2024-07-26 13:09 UTC, rprospero commented on src/math/data1D.h
> +    std::pair<double, double> nNonZeroValues() const;
If you use my suggestion from above, you'll need to update the type here from a pair to a tuple.  It's also probably worth updating the name and the comment, since the function does not return the *number* of non-zero values, but the values themselves.

2024-07-26 13:09 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +            }
```suggestion
            case TargetPropertyType::Mass:
                // Atomic mass
                value = AtomicMass::mass(atomicNumber);
                break;
            case TargetPropertyType::AtomicNumber:
                // Atomic number
                value = atomicNumber;
                break;
            case TargetPropertyType::ScatteringLengthDensity:
                auto naturalIsotope = Sears91::naturalIsotope(atomicNumber);

                // Bound coherent natural isotope scattering length density
                value = Sears91::boundCoherent(naturalIsotope);
                break;
```

Cases for switch statements don't take braces.

2024-07-26 13:09 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +                       [&hist](auto &value) { hist.bin(value / voxelVolume); });
```suggestion
    for(const auto &value: data3D.values())
        hist.bin(value / voxelVolume);
```

I feel like the most contrary and obnoxious reviewer for even making this suggestion, but I think that we might be better off here with just a for loop.  I'm always the guy pushing to move things into the standard algorithms, but there's a couple of reasons that I make an exception here.

1. Unless I'm missing something, you've failed to capture the `voxelVolume` term in the lambda, which should be a compile time error.  We don't have to worry about that with for loops.
1. Unlike most algorithms, `std::for_each` doesn't really inform the compiler.  The nice part about algorthims is that the compiler known more about what we're trying to accomplish and can use that for better optimizations.  `std::for_each` tells the compiler that we're doing this entirely for the side effects, so there's no advantage there over a plain for loop
2. Unlike plain for-loops, `for_each` does have the advantage that it can be run in parallel.  However, we both know what a nightmare it can be to try and bin a histogram in parallel, so this loop will pretty much always be sequential.
3. The other big advantage to algorithms comes from refactorings.  It's easy to turn a `std::copy` into a `std::transform` if your requirements change down the line (all it takes is an extra lambda).  However, since `hist.bin` is such a pain to refactor, that's not likely to happen.  Even if we did find a better solution, it would mot likely no wind up sharing any code with the `for_each` solution.  For example, if we found a good way to do the binning in parallel, we would want it everywhere in the code, not just here.  That would mean that it would likely become part of the Data3D code and the actual result would look something closer to

```cpp
hist.bin_values(data3D.values(),
    [voxelVolume](auto v){return v/voxelVolume;}
);
```
which shares essentially zero code with the `for_each` call.

I'm sorry that this turned into an essay and I'm happy to listen to any arguments you might have for keeping this in a `for_each` call.  I just felt that you deserve some justification when I suddenly pull out "just use a for loop".

2024-07-26 13:09 UTC, rprospero commented on tests/modules/voxelDensity.cpp
> +    ASSERT_NEAR(max8Bin.second, std::pow(8, 3));
This looks like a nice test setup, but I'll admit that I'm not quite sure what it's testing.  Some extra comments would be helpful in here.

The best understanding that I had was that you're populating each voxel with a single Helium atom and then confirm that it's reading out the correct unit of value from the voxel density.  What I'm not quite understanding is why the maximum value is always supposed to be in the final voxel?

2024-07-26 14:13 UTC, RobBuchananCompPhys commented on src/math/data1D.h
> +    std::pair<double, double> nNonZeroValues() const;
Thanks!

2024-07-26 14:15 UTC, RobBuchananCompPhys commented on src/math/data1D.cpp
> +
Sounds ideal

2024-07-26 15:07 UTC, RobBuchananCompPhys commented on tests/modules/voxelDensity.cpp
> +    ASSERT_NEAR(max8Bin.second, std::pow(8, 3));
It's testing that different partitioning schemes applied to the unit cell (i.e. diving axes into 8, 4, 2, 1 bins and therefore 8^3, 4^3, 2^3, 1 voxels) result in the same value being binned - in this case, since the system is always 8x8x8 evenly spaced Helium atoms, we expect to always and only be hitting the Mass(He) / Z(He) / SLD(He) per cubic angstrom bin. The maximum value is in the `second` member of the pair returned from `maxValueAt`, and since no other values are being binned (we hope), this will be the maximum value in the series.

2024-07-26 15:13 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +                       [&hist](auto &value) { hist.bin(value / voxelVolume); });
No worries at all, I really welcome this level of feedback! Its good to get a long-term take on how the code might evolve, and I'm mindful to take this into consideration (as you alluded to, the histogram parallelisation hasn't been easy). I'm happy to make this change.

2024-07-30 10:11 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +        }
My feeling is that having a trio of unary operators tailored to the specific quantities would make this cleaner and more efficient.

2024-07-30 10:11 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +        GenericItem::InRestartFileFlag);
When naming the output data we shouldn't worry about appending the name of the property being calculated since the module explicitly deals with one and one only.

2024-07-30 10:11 UTC, trisyoungs commented on src/modules/voxelDensity/voxelDensity.cpp
> +    keywords_.add<IntegerKeyword>("NumberOfPoints", "Number of points over which analysis is performed", numPoints_, 1);
Feels like there's a better name to be had than "NumberOfPoints".  Perhaps "NVoxelsPerSide" or just "NVoxels"?

2024-07-30 11:02 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/voxelDensity.cpp
> +    keywords_.add<IntegerKeyword>("NumberOfPoints", "Number of points over which analysis is performed", numPoints_, 1);
`NVoxels` sounds succinct and to the point!

2024-07-30 12:08 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +        GenericItem::InRestartFileFlag);
Is there somewhere else we can officialise the units being used (i.e. the histogram bins will be in per cubic angstrom), perhaps I can add that to the module keyword description, and I guess the gui part will reflect that too

2024-08-14 09:04 UTC, closed without merging