feat: TR module added
trisyoungs/duq pull request #1956
Opened 2024-06-27 15:51 UTC by Danbr4d

Closes #1950

2024-07-02 08:20 UTC, trisyoungs requested changes, later dismissed
A bunch of small comments just to tidy things up. Hopefully all my deletions don't break it!

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/gui/trWidget.h
> +    void on_ConfigurationTargetCombo_currentIndexChanged(int index);
These functions are irrelevant here and can be removed.

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/gui/trWidgetFuncs.cpp
> +
Not required any more - this is very old legacy stuff!
```suggestion
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/gui/trWidgetFuncs.cpp
> +                                                      fmt::format("{} (Unbound)", id), "Unbound");
Are you calculating the bound and unbound partials, or just the full partial? If only the latter then the bound and unbound ones can be removed.  Also, the total T(r) isn't created and displayed here if the "Totals" button is enabled.

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/gui/trWidgetFuncs.cpp
> +}
Not required - these can be removed as can the controls in the UI.

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/gui/trWidget.h
> +    void on_TotalsButton_clicked(bool checked);
Only dealing with one set of partials and one total function, so I would suggest renaming these:
```suggestion
    void on_PartialsButton_clicked(bool checked);
    void on_TotalButton_clicked(bool checked);
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +            "[SETUP {}] Target '{}' doesn't source any S(Q) data, so it can't be used as a target for the EPSR module.", name_,
```suggestion
            "Target module '{}' doesn't source any S(Q) data, so it can't be used as a target for the TR module.",
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +        Messenger::error("[SETUP {}] A source NewutronSQ module must be provided.\n", name_);
```suggestion
        Messenger::error("A source NeutronSQ module must be provided.\n");
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +        Messenger::error("[SETUP {}] A source GR module (in the SQ module) must be provided.\n", name_);
```suggestion
        Messenger::error("A source GR module (in the target SQ module) must be set.\n");
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +        {
```suggestion
    for (auto typeI = 0; typeI < unweightedtr.nAtomTypes(); ++typeI)
    {
        for (auto typeJ = typeI; typeJ < unweightedgr.nAtomTypes(); ++typeJ)
        {
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +            weightedtr.partial(typeI, typeJ) += weightedtr.boundPartial(typeI, typeJ);
Why add in the bound partial here?

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +            }
You could move the factor completely outside the loop like this if you wanted to:
```suggestion
            auto factor = 4.0 * PI * rho.value() * weights.atomTypes()[typeJ].fraction();

            for (auto &&[x, y] : zip(weightedtr.partial(typeI, typeJ).xAxis(), weightedtr.partial(typeI, typeJ).values()))
            {
                y *= factor * x;
            }
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +    // Sum into total
```suggestion

    // Sum into total
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.cpp
> +        "UseHalfCellRange", "Whether to use the maximal RDF range possible that avoids periodic images", deprecatedBool_);
```suggestion
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.cpp
> +#include "keywords/optionalInt.h"
```suggestion
#include "keywords/module.h"
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.h
> +#include "math/function1D.h"
```suggestion
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.h
> +class ModuleGroup;
```suggestion
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.h
> +// RDF Module
```suggestion
// TR Module
```

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.h
> +    PartialSet weightedtr;
Not required as we're retrieving / storing this data dynamically from / to processingModuleData_.

2024-07-02 08:20 UTC, trisyoungs commented on src/modules/tr/tr.h
> +     */
```suggestion
```

2024-07-02 08:34 UTC, trisyoungs commented on src/modules/tr/process.cpp
> +    // Calculate and store weights
```suggestion
    // Retrieve weights
```

2024-09-03 12:41 UTC, Danbr4d commented
The partial tr's are far too large at the moment but the total TR looks good. Makes me think that maybe what I'm displaying is wrong and not the equation potentially.

2024-09-04 12:46 UTC, Danbr4d commented
Can't figure out the issue with this one. I can't see where the large partialTR is coming from and not being output in the same way.

2024-10-30 14:31 UTC, rprospero approved these changes

2024-10-30 14:34 UTC, merged