Feat/voxel density module ty
trisyoungs/duq pull request #1964
Opened 2024-08-09 09:10 UTC by RobBuchananCompPhys

2024-08-20 08:33 UTC, trisyoungs commented on src/gui/icons/modules/VoxelDensity.svg
I like it!

2024-08-20 08:33 UTC, trisyoungs commented on src/gui/icons/modules/VoxelDensityt.svg
Random other icon?

2024-08-20 08:33 UTC, trisyoungs commented on src/math/data1D.cpp
> +        return {0.0, 0.0};
```suggestion
        return {0, 0.0};
```

2024-08-20 08:33 UTC, trisyoungs commented on src/math/data1D.cpp
> +
I would be tempted to follow Dissolve's unwritten rule of keeping the `Data*D` classes as simple as possible in terms of functionality, and adding stuff like this to a functional namespace as we do for things like `Filter`, `Averaging` - `Limits` would be a good choice here.

2024-08-20 08:33 UTC, trisyoungs commented on src/math/data1D.cpp
> +std::pair<size_t, double> Data1D::maxValueAt()
Same comment as above.

2024-08-20 08:33 UTC, trisyoungs commented on src/math/data3D.cpp
> +}
This function feels extremely dangerous!  The `x_`, `y_`, and `z_` arrays are being extended, but the `values_` array is already the correct size? What if non-contiguous values of x, y, and/or z are passed?
Is this functional actually used anywhere?

2024-08-20 08:33 UTC, trisyoungs commented on src/math/data3D.cpp
> +    }
Again, extending `Data3D` in this way feels very risky!

2024-08-20 08:33 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +    return Vec3<double>(x, y, z);
This is modifying the actual coordinates of the `Atom` and, while it's only a fold operation, we should be as read-only as possible on a `Configuration`, especially for analysis-type modules which aren't expected to modify contents.

If you change the function signature to just take the non-const `Vec3<double> r` of the atom coordinates, then you can do:
```suggestion
    return unitCell->foldFrac(r);
```
You may even wish to remove the function altogether and just do it in place since it's only one line.

2024-08-20 08:33 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +    auto atoms = targetConfiguration_->atoms();
Here you're taking a copy of the entire atoms array which is going to be expensive and might cause issues with other object relationships.
```suggestion
    const auto &atoms = targetConfiguration_->atoms();
```

2024-08-20 08:33 UTC, trisyoungs commented on src/modules/voxelDensity/voxelDensity.h
> +class Configuration;
```suggestion
// Forward Declarations
class Configuration;
```

2024-08-20 08:33 UTC, trisyoungs commented on src/modules/voxelDensity/voxelDensity.cpp
> +    keywords_.add<IntegerKeyword>("NAxisVoxels", "Number of points per axis over which analysis is performed", nAxisVoxels_, 1);
I think here we would make things easier and more intuitive for the user if we took a rough requested voxel length, rather than the number of points along each cell axis.  A default value of `3.0` would give you a requested voxel cube of 27 cubic Angstroms, not too far off the volume of a single water molecule. Of course, the requested value wont always multiply as a whole integer along an axis, so we will need to adjust the requested size based on the actual axis lengths.  This also solves the problem of calculating the voxel density on a non-cubic box shape which may have very different axis lengths - as written, we would get quite non-uniform voxels.

2024-08-20 08:33 UTC, trisyoungs commented on src/templates/array3D.h
> +    std::vector<A> &values() { return array_; }
Tens to write these without a separate comment for the overload
```suggestion
    // Return reference to values
    std::vector<A> &values() { return array_; }
    const std::vector<A> &values() const { return array_; }
```

2024-08-20 08:33 UTC, trisyoungs commented on src/templates/array3D.h
> +
Just wondering - would we also have issues here if just one dimension was `1`? A very long stick, or a plane?  Perhaps its worth capturing this in a unit test specifically for the `Array3D`.

2024-08-20 08:33 UTC, trisyoungs commented on tests/modules/voxelDensity.cpp
> +} // namespace UnitTest
Will we try to implement this?

2024-08-20 08:36 UTC, RobBuchananCompPhys commented on tests/modules/voxelDensity.cpp
> +} // namespace UnitTest
Yes, we will!

2024-08-20 08:38 UTC, RobBuchananCompPhys commented on src/math/data1D.cpp
> +
Agreed, I'll address this

2024-08-20 08:41 UTC, RobBuchananCompPhys commented on src/math/data3D.cpp
> +}
This is not actually being used anywhere. I see your point about safety, and I've been uncomfotable about this bit of code since writing it but didn't get round to removing it yet - I think it should go.

2024-08-20 10:19 UTC, RobBuchananCompPhys commented on src/gui/icons/modules/VoxelDensityt.svg
shouldn't be there, I think it is a copy

2024-08-30 08:07 UTC, RobBuchananCompPhys commented on src/templates/array3D.h
> +
I'll look at moving this check outside of the `Array3D` class - think all we need to do is check that the number of voxels is 1, and in that case we get the `array[0]`, else we use the `operator[]` as normal.

2024-09-02 14:07 UTC, rprospero reviewed
I have some suggestions and some questions.  Most of the suggestions are fairly trivial, but I'm a bit worried about the questions before we go forward.

2024-09-02 14:07 UTC, rprospero commented on src/math/limitsFunc.h
> +    return {std::distance(values.begin(), result), *result};
```suggestion
    return {result - values.begin(), *result};
```

I find the subtraction to be slightly more readable, but I know that sometimes `std::distance` helps clean up a problem.

2024-09-02 14:07 UTC, rprospero commented on src/templates/array3D.h
> +        */
Remove dead code?

2024-09-02 14:07 UTC, rprospero commented on src/modules/voxelDensity/voxelDensity.h
> +    const double voxelVolume() { return voxelVolume_; }
```suggestion
    double voxelVolume() const { return voxelVolume_; }
```

Did you mean for this to be a const function?  I'm not sure why it would otherwise need to return a `const double`

2024-09-02 14:07 UTC, rprospero commented on src/modules/voxelDensity/voxelDensity.h
> +    VoxelDensityModule::TargetPropertyType getCurrentProperty() { return targetProperty_; }
```suggestion
    VoxelDensityModule::TargetPropertyType getCurrentProperty() const { return targetProperty_; }
```

Make this a const function

2024-09-02 14:07 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +    array[t] += value;
I'm a little concerned why we need the special case for the single element voxel.  If the array accessors doesn't work properly in than instance, are we sure that it works in the other insances.  For instance, if the x and y width are 1, but z is two, does it still give the right answer?

If the tuple access does give the right answer, could we drop the special case?

2024-09-02 14:07 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +            }
```suggestion
            bool included = std::any_oF(restricToToSpecies_.begin(), restrictToSpecies_.end(), [sp](auto &spTarget) {return sp->name() == spTarget->name();});
```

Might be a good place to use `std::any_of`

2024-09-02 14:07 UTC, rprospero commented on src/modules/voxelDensity/process.cpp
> +            }
```suggestion
            if (included)
                targetConfiguration_->removeMolecules(sp);
```

2024-09-02 14:39 UTC, trisyoungs commented on src/math/mathFunc.cpp
> +double log10(double x) { return std::log10(x); }
Is this something we need to wrap in our own functions? The only benefit is with the pure `int` version, and even then I'm not sure that `DissolveMath::log(n)` is better than `int(std::log(n))`.

2024-09-02 14:39 UTC, trisyoungs commented on src/modules/voxelDensity/gui/voxelDensityWidgetFuncs.cpp
> +            return "Scattering length density, cm\\sup{-2}";
Should these x-axis labels by in units of X per voxel or per Angstrom**3?

2024-09-02 14:39 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +    array3D.initialise(nAxisVoxels_.x, nAxisVoxels_.y, nAxisVoxels_.z);
Since this `Array3D` is not saved to the restart file there is no need / utility in using the `realise()` function here. Also, we are recreating it every time the module runs, where we could just create it once the first time its used and then zero the values in it on subsequent uses.

2024-09-02 14:39 UTC, trisyoungs commented on src/modules/voxelDensity/voxelDensity.h
> +    const double voxelVolume() { return voxelVolume_; }
Only a small thing, but we don't define even trivial functions in headers.

2024-09-02 14:39 UTC, trisyoungs commented on tests/data/dissolve/input/voxelDensity-helium-Z.txt
These test files could mostly be removed leaving only a single one which we can use in a loop, setting the voxel size and quantity type programmatically in the unit test.

2024-09-02 16:09 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/gui/voxelDensityWidgetFuncs.cpp
> +            return "Scattering length density, cm\\sup{-2}";
That's correct I think, thanks for pointing it out!

2024-09-02 16:18 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +            }
Agreed

2024-09-03 07:34 UTC, RobBuchananCompPhys commented on src/math/mathFunc.cpp
> +double log10(double x) { return std::log10(x); }
In that case, probably not.

2024-09-03 07:37 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +    array[t] += value;
This seems to have been a totally unnecessary check - it most likely arose from an oversight on my part where I was using `std::round`, and in the case of a single voxel was rounding up to `0.something * 1 voxel = 1`, and therefore `Array3D` couldn't index it (since there is no `array[1]` to access). Changing to `std::floor` fixed this a while back, and I've removed the check.

2024-09-03 13:08 UTC, trisyoungs commented on src/math/limitsFunc.h
> +    std::vector<double>::iterator result = std::max_element(values.begin(), values.end());
```suggestion
    auto result = std::max_element(values.begin(), values.end());
```

2024-09-05 09:13 UTC, trisyoungs requested changes
Sorry - just spotted one significant thing that needs changing!
Also I am the Blank Line Police today. :smile:

2024-09-05 09:13 UTC, trisyoungs commented on src/modules/voxelDensity/process.cpp
> +    }
Just spotted this - this will have the desired effect of restricting the calculation to the listed species, but it is destructive in the sense that it is actually removing molecules from the `Configuration`. If you look at the `MolShake` you'll see that we have to construct a list of `Molecule`s that we work over, based on the `Species` pointers in the `restrictToSpecies_` vector, and then the main loop runs over these molecules.

Either we need to rework the module to work in this way, or we remove the restrict-to-species functionality for the time being and add it in later.

2024-09-05 09:13 UTC, trisyoungs commented on src/modules/voxelDensity/voxelDensity.h
> +
```suggestion
```

2024-09-05 09:13 UTC, trisyoungs commented on src/templates/array3D.h
> +
```suggestion
```

2024-09-06 08:42 UTC, RobBuchananCompPhys commented on src/modules/voxelDensity/process.cpp
> +    }
Removed

2024-09-10 10:20 UTC, trisyoungs approved these changes
Good to go. :+1:

2024-09-10 10:33 UTC, merged