fitting funcs - peak finding
trisyoungs/duq pull request #1978
Opened 2024-09-27 08:29 UTC by RobBuchananCompPhys

2024-10-30 14:26 UTC, rprospero requested changes
Your numerical methods background is both more recent and more intensive than mine, so my suggestions might be out of line due to my missing crucial details.  In that case, many of my comments could be corrected with just some explanatory comments.

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.cpp
> +        return peaks;
This means that the `isolation_` parameter is ignored in the specific instance where the length of the array equals `n`.  This can cause number of peaks to change wildly by simply incrementing the value by one.  If this is intended, then we probably need a comment explaining why.

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.cpp
> +std::vector<Peaks::Peak1D> Peaks::top(int n, std::vector<Peaks::Peak1D> peaks)
```suggestion
std::vector<Peaks::Peak1D> Peaks::top(std::size_t n, std::vector<Peaks::Peak1D> peaks)
```

This is pedantic, but `n` must logically be between 0 and the largest possible size of `peaks`, which is the exact definition of `std::size_t`.  If also saves us and `abs` call later on.

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.h
> +    // Calculate prominences of peaks
It might be worth explaining what is meant by prominence here

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.cpp
> +        }
As I understand these lines, you're mostly just looking for the range on each side of the peak where the values are strictly decreasing.  This can be accomplished with the `std::is_sorted_until` algorithm.  That would also be robust against the peak reaching the end of the value, which *looks* like a bug in this setup (e.g. when iLeft=0, the `heightRefLeft` is never set).

On a related note, it feels that `heightRefLeft` should be set with a mere `=` instead of a `+=`, unless there is something that I'm not understand.

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.h
> +    bool isInflectionPoint(double *points);
Instead of passing a pointer, it might be better to pass a `std::array<double, 3>`.  This allows the compiler to ensure that the function always has access to three values.

2024-10-30 14:26 UTC, rprospero commented on src/math/peaks.cpp
> +        auto isolatedPeaks = top(std::round(maxX / isolation_), peaks);
I'm curious about the choice of `std::round(maxX / isolation_)` for the number of peaks.  As my mental example, I'm imagining taking may data and padding the end with a ton of zeroes.  The function would now start returning more peaks in the exact same data, just because maxX has increased, despite the fact that all the peaks are still in that same unpadded data.

I'm thinking that we might be better off with the `top` function not taking a count at all and simply returning all of the peaks that match the isolation requirements.

2024-10-30 17:29 UTC, RobBuchananCompPhys commented on src/math/peaks.h
> +    bool isInflectionPoint(double *points);
Always wanted a reason to use `std::array`!

2024-10-30 18:06 UTC, RobBuchananCompPhys commented on src/math/peaks.cpp
> +        return peaks;
Good catch. I'm tempted to go with removing the contentious `if` statement and just let the function run without checking if `n == peaks.size()` - I think it's better to always give the `isolation_` chance to take effect.
I say this because in one case, the function is called with zero `isolation_` set, so we will just get back N peaks, ordered by height. In the other case, `isolation_` is non-zero, and the resulting effect is that the isolation radius cuts out a few of the supplied peaks before returning - which is exactly what we'd expect if the object has isolation set on it.

2024-11-01 16:16 UTC, RobBuchananCompPhys commented on src/math/peaks.cpp
> +        auto isolatedPeaks = top(std::round(maxX / isolation_), peaks);
Cheers for pointing this out. The padding out thought experiment is definitely an issue in the current configuration.
I have an idea though - how about instead of removing the explicit target count argument from `top`: what we actually do is replace `std::round(maxX / isolation_)` with `std::round((peaks.back().valueAt - peaks.front().valueAt) / isolation_)`. That way, even if you were to pad out the same data with tonnes of zeros, the ratio of peaks to isolation radius would always be constrained by the actual location of the peaks, which doesn't change when the `Peak1D` vector is passed to `top`.
A user could still call `top` in any other situation with a target integer N and get the N top peaks, but when it's called in `find` as here, it could still handle the logic without the user actually knowing what N was used.

2024-11-01 16:18 UTC, RobBuchananCompPhys commented on src/math/peaks.cpp
> +        }
No, you're correct, there was no need to increment after initialising `heightRef` - I have changed it to `=`

2024-11-01 16:18 UTC, RobBuchananCompPhys commented on src/math/peaks.cpp
> +        }
The whole method has been refactored in a more simple way that I think better encapsulates the prominence computation.

2024-11-05 09:26 UTC, RobBuchananCompPhys commented
@rprospero FYI - I attach [documentation from Mathworks](https://uk.mathworks.com/help/signal/ug/prominence.html) detailing the prominence algorithm we're using here.

2024-11-05 09:43 UTC, RobBuchananCompPhys commented on src/math/peaks.cpp
> +        auto isolatedPeaks = top(std::round(maxX / isolation_), peaks);
Actually I think it would be `std::round((peaks.back().valueAt - peaks.front().valueAt) / (isolation_*2))`, since `isolation_` is a radius, so were looking to see how many full isolation zones fit into the space between the first and last peak. 

Note: If user has set something like isolation = 0.000001, then `top` might get called with a large `n` relative to the number of actual detected peaks, but the function exits when it has reached all the peaks so that shouldn't be an issue.

2024-11-05 12:21 UTC, rprospero approved these changes

2024-11-05 17:30 UTC, merged