fix: Visit each pair in TR module
trisyoungs/duq pull request #1980
Opened 2024-09-27 09:48 UTC by rprospero

This should alter the TR process to visit each ordered pair.

2024-10-01 15:07 UTC, Danbr4d commented on src/modules/tr/process.cpp
> +        true);
Shouldn't this be false as we do want to go through all the pairs

2024-10-14 08:22 UTC, trisyoungs requested changes

2024-10-14 08:22 UTC, trisyoungs commented on src/classes/partialSet.cpp
> +        for_each_pair_early(atomTypeMix_.begin(), atomTypeMix_.end(),
Why are we duplicating the whole code block and not just passing `half_` as the last argument to `for_each_pair_early`?

2024-10-14 08:22 UTC, trisyoungs commented on src/classes/partialSet.cpp
> +void PartialSet::setFullMatrix() { half_ = false; }
I think this is quite a dangerous way of doing things, since I can freely set `half_` and it will have no impact on the arrays themselves.  A more robust solution would be to pass an additional argument to the `setUpPartials()` functions.

2024-10-14 08:22 UTC, trisyoungs commented on src/classes/partialSet.cpp
> +    parser.hasArg(1) ? half_ = parser.argb(1) : half_ = true;
```suggestion
    half_ = parser.hasArg(1) ? parser.argb(1) : true;
```

2024-10-14 08:22 UTC, trisyoungs commented on src/classes/partialSet.cpp
> +    if (half_)
Here too you can just pass `half_` as the last argument to `for_each_pair_early()`.

2024-10-23 14:30 UTC, trisyoungs reviewed
One small stylistic correction, but can't see anything obviously wrong with this PR. I'll run it for a bit and do some testing.

2024-10-23 14:30 UTC, trisyoungs commented on src/classes/partialSet.h
> +    bool half_ = true;
```suggestion
    bool half_{true};
```

2024-10-25 12:47 UTC, trisyoungs approved these changes
Looking good!  One minor change suggestion to use another algorithm, but that's it.

2024-10-25 12:47 UTC, trisyoungs commented on src/classes/partialSet.cpp
> +                continue;
You could turn this into a use of `for_each_pair_early` for consistency:
```
    auto success = for_each_pair_early(
        0, nTypes,
        [&](int typeI, int typeJ) -> EarlyReturn<bool>
        {
            auto &part = partials_[{typeI, typeJ}];
            auto &bound = boundPartials_[{typeI, typeJ}];
            ... etc ...
            return EarlyReturn<bool>::Continue;
        },
        half_};

    if (!success.value_or(true))
        return false;
```

2024-10-28 09:45 UTC, merged