feat: initial addition of potentialSet class
trisyoungs/duq pull request #1991
Opened 2024-10-22 15:13 UTC by Danbr4d

Addition of potentialSet class for easier averaging of potentials.

2024-10-25 10:55 UTC, rprospero commented on src/classes/potentialSet.cpp
> +
```suggestion
    for (auto &[key, value] : potentials_)
    {
        if (!parser.writeLineF("{} {} {} {}\n", key, value.count, value.at1->name(), value.at2->name()))
            return false;
        if (!value.ep.serialise(parser))
            return false;
    }
```

2024-10-25 11:03 UTC, rprospero commented on src/classes/potentialSet.cpp
> +
```suggestion
    
    if (parser.getArgsDelim(LineParser::Defaults) != LineParser::Success)
        return false;
    auto size = parser.argli(0);
    for (auto n = 0; n < size; ++n)
    {
        if (parser.getArgsDelim(LineParser::Defaults) != LineParser::Success)
            return false;
        EPData value;
        auto key = parser.args(0);
        value.count = parser.argi(1);
        value.at1 = coreData.findAtomType(parser.args(2));
        value.at2 = coreData.findAtomType(parser.args(3));
        
        if (!value.ep.deserialise(parser))
            return false;
            
        potentials_[key] = value;
    }

```

2024-11-05 11:47 UTC, rprospero submitted a review, later dismissed
Two bits here.  First, I've made some suggestions on the operators.  Also, we should probably add a unit test for the averaging.  It'll be easier to put it in now while the code is fresh in your mind than six months from now when we're tracking down a bug.

2024-11-05 11:47 UTC, rprospero commented on src/classes/potentialSet.cpp
> +}
```suggestion
PotentialSet& PotentialSet::operator+=(const double delta)
{
    for (auto &[key, potential] : potentials_)
        potential.ep += delta;
    return (*this);
}

PotentialSet& PotentialSet::operator+=(const PotentialSet &source)
{
    for (auto &[key, potential] : source.potentialMap())
        potentials_[key].ep += potential.ep;
    return (*this);
}

PotentialSet& PotentialSet::operator*=(const double factor)
{
    for (auto &[key, potential] : potentials_)
        potential.ep *= factor;
    return (*this);
}
```

A couple of changes here.  First, we're dropping the extra braces on the single line `for` loop.  I'm also having the operator return a reference to the value.  This is generally good practice for the assignment operators because it enables chaining.  For example,

```
  a += b += c
```

Honestly, if someone ever submitted code like that, it's not going to get through code review.  Still, I think that the compiler is a little happier if that is available, so we should leave it in.

2024-11-05 11:47 UTC, rprospero commented on src/classes/potentialSet.h
> +    void operator*=(const double factor);
```suggestion
    PotentialSet& operator+=(const double delta);
    PotentialSet& operator+=(const PotentialSet &source);
    PotentialSet& operator*=(const double factor);
```

Matchthing the changes I made to the operators.

2024-11-18 14:02 UTC, trisyoungs commented on src/modules/epsrManager/process.cpp
> +
Could this section be the issue?  The logic here doesn't quite add up, since you store the current potentials as the beginning of `averagePotentials`, then add `potentials` to the store, then immediately remove it if you have exceeded your averaging length (which past a certain point you always will) and then do the sum over all the store potentials. That will give you N+1 sets of potentials contributing to the average, rather than the N you want, and which will always contain the first N potential sets you ever generate at the beginning of the simulation (since you're doing `pop_back` rather than `pop_front`. The `Averaging` class would sort all this out for you, but I have suggested the necessary modifications to clean this up anyway.

2024-11-18 14:02 UTC, trisyoungs commented on src/modules/epsrManager/process.cpp
> +    averagedPotentialsStore.emplace_back(potentials);
```suggestion
```

2024-11-18 14:02 UTC, trisyoungs commented on src/modules/epsrManager/process.cpp
> +    }
```suggestion
    // Limit data to average to the most recent N-1 sets
    while (averagedPotentialsStore.size() >= averagingLength_)
    {
        averagedPotentialsStore.pop_front();
    }
```

2024-11-18 14:02 UTC, trisyoungs commented on src/modules/epsrManager/process.cpp
> +    potentials = averagedPotentials;
```suggestion
    // Add the current potentials (before averaging) to the average store before we overwrite them
    averagePotentialsStore.emplace_back(potentials);

    // Set new averaged potentials
    potentials = averagedPotentials;
```

2024-11-18 14:02 UTC, trisyoungs commented on src/modules/epsrManager/process.cpp
> +            averagedPotentials[key].ep /= averagingLength_.value();
You definitely don't want to do this division every time you add a set of potentials, just once at the end!

2025-01-09 13:22 UTC, trisyoungs requested changes
I've requested changes on this but its just object naming and comment correction.

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +// Set of Partials
```suggestion
// Set of Potentials
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.cpp
> +// Reset partial arrays
```suggestion
// Reset
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    // Reset partial arrays
```suggestion
    // Reset```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    // Pair matrix, containing full atom-atom partial
```suggestion
    // Map of named potentials to data
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    struct EPData
I want to say that we should rename this because there isn't any reason why it has to have empirical potential (EP) data in it:
```suggestion
    struct PotentialData
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +        Data1D ep;
```suggestion
        Data1D potential;
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    std::map<std::string, EPData> potentials_;
```suggestion
    std::map<std::string, PotentialData> potentials_;
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    // Return fingerprint of partials
```suggestion
    // Return fingerprint
```

2025-01-09 13:22 UTC, trisyoungs commented on src/classes/potentialSet.h
> +    // Return full atom-atom partial specified
```suggestion
    // Return full map of potentials specified
```

2025-01-17 14:15 UTC, trisyoungs approved these changes
Two more small things in comments I just spotted, then good to go.

2025-01-17 14:15 UTC, trisyoungs commented on src/modules/epsrManager/epsrManager.h
> +    // Weighting scheme to use when averaging partials
```suggestion
    // Number of historical potential sets to combine into final partials
    std::optional<int> averagingLength_;
    // Weighting scheme to use when averaging potential
```

2025-01-17 14:56 UTC, merged